import type { ToolConfig } from "./toolsConfig";

export const SALESFORCE_TOOLS: ToolConfig[] = [
  {
    slug: "cron-generator",
    title: "Salesforce Cron Expression Generator",
    shortDescription: "Generate valid Salesforce cron expressions for scheduled Apex and Flow jobs.",
    category: "salesforce",
    icon: "Clock",
    gradient: "from-blue-600 to-indigo-600",
    badge: "Scheduler",
    popular: true,
    seo: {
      title: "Salesforce Cron Expression Generator | Free Scheduler Tool | Ranburg",
      description:
        "Free Salesforce cron generator. Build valid cron expressions for Schedulable Apex, Flow scheduled paths, and batch jobs. Copy-ready output with examples.",
      keywords: ["Salesforce cron generator", "Salesforce scheduler", "cron expression Salesforce", "Schedulable Apex cron"],
    },
    howToUse: [
      "Select frequency: hourly, daily, weekly, or monthly.",
      "Choose the time, day, and month settings for your schedule.",
      "Review the generated cron expression in Salesforce format.",
      "Copy and paste into your Schedulable class or Flow scheduled trigger.",
    ],
    formula: "Salesforce cron format: Seconds Minutes Hours Day_of_month Month Day_of_week Optional_year",
    faq: [
      { question: "What cron format does Salesforce use?", answer: "Salesforce uses a 6- or 7-field cron expression: Seconds Minutes Hours Day_of_month Month Day_of_week Optional_year. Seconds are required unlike Unix cron." },
      { question: "Can I schedule a Flow with cron?", answer: "Yes. Scheduled Flows and Scheduled Paths use the same cron syntax. Test in sandbox before production." },
      { question: "What is the minimum interval?", answer: "Salesforce scheduled jobs can run at minimum once per hour for most org types. Verify governor limits for your edition." },
    ],
  },
  {
    slug: "formula-generator",
    title: "Salesforce Formula Generator",
    shortDescription: "Build formulas for fields, flows, and validation rules with guided templates.",
    category: "salesforce",
    icon: "FunctionSquare",
    gradient: "from-sky-500 to-blue-600",
    badge: "Formula Builder",
    popular: true,
    seo: {
      title: "Salesforce Formula Generator | Free Formula Builder | Ranburg",
      description:
        "Generate Salesforce formulas for formula fields, validation rules, and flows. IF, CASE, TEXT, DATE, and cross-object formula templates with copy-ready output.",
      keywords: ["Salesforce formula generator", "Salesforce formula builder", "Salesforce IF formula", "formula field generator"],
    },
    howToUse: [
      "Choose a formula type: IF, CASE, TEXT, DATE, or BLANKVALUE.",
      "Enter field API names and comparison values.",
      "Preview the generated formula syntax.",
      "Copy into Formula Field, Validation Rule, or Flow formula resource.",
    ],
    formula: "IF(logical_test, value_if_true, value_if_false) — nested IFs handle multiple conditions.",
    faq: [
      { question: "Can I use this for validation rules?", answer: "Yes. Generated formulas work in formula fields, validation rules, workflow field updates, and Flow formula resources." },
      { question: "What return types are supported?", answer: "Checkbox, Text, Number, Date, and DateTime return types depending on the template selected." },
      { question: "Are cross-object formulas supported?", answer: "Use the template and replace merge fields with valid cross-object relationship paths like Account.Name." },
    ],
  },
  {
    slug: "soql-builder",
    title: "Salesforce SOQL Query Builder",
    shortDescription: "Visually build SOQL queries with filters, joins, and aggregations.",
    category: "salesforce",
    icon: "Search",
    gradient: "from-cyan-500 to-teal-600",
    badge: "SOQL Tool",
    popular: true,
    seo: {
      title: "Salesforce SOQL Builder | Free SOQL Query Generator | Ranburg",
      description:
        "Free SOQL query builder for Salesforce. Select objects, fields, WHERE clauses, ORDER BY, and LIMIT. Generate copy-ready SOQL for Developer Console and Apex.",
      keywords: ["SOQL builder", "Salesforce SOQL generator", "SOQL query builder", "Salesforce query tool"],
    },
    howToUse: [
      "Enter the primary sObject API name (e.g., Account, Opportunity).",
      "Add fields to SELECT clause.",
      "Define WHERE conditions with operators (=, !=, IN, LIKE).",
      "Set ORDER BY and LIMIT, then copy the SOQL query.",
    ],
    formula: "SELECT fields FROM Object WHERE conditions ORDER BY field LIMIT n",
    faq: [
      { question: "Does this support relationship queries?", answer: "Yes. Use relationship dot notation like Account.Name or Contact.Account.Industry in the field list." },
      { question: "Can I use aggregate functions?", answer: "Enable aggregate mode to add COUNT(), SUM(), AVG(), MIN(), MAX() with GROUP BY." },
      { question: "Is SOQL injection safe?", answer: "Always bind variables in Apex. This tool generates static queries for development and testing only." },
    ],
  },
  {
    slug: "validation-rule-generator",
    title: "Salesforce Validation Rule Generator",
    shortDescription: "Create validation rule formulas with error messages and field-level guidance.",
    category: "salesforce",
    icon: "ShieldCheck",
    gradient: "from-emerald-500 to-green-600",
    badge: "Data Quality",
    seo: {
      title: "Salesforce Validation Rule Generator | Free Rule Builder | Ranburg",
      description:
        "Generate Salesforce validation rules with formulas and error messages. Required fields, format checks, cross-field logic, and regex patterns.",
      keywords: ["Salesforce validation rule generator", "validation rule formula", "Salesforce data validation"],
    },
    howToUse: [
      "Select validation type: required, format, range, or custom logic.",
      "Enter field API names and conditions.",
      "Write a user-friendly error message.",
      "Copy formula and message into Setup → Validation Rules.",
    ],
    formula: "AND(condition1, condition2) — rule fires when formula evaluates to TRUE (blocks save).",
    faq: [
      { question: "When does a validation rule fire?", answer: "Validation rules run on insert and update when the formula evaluates to TRUE, preventing the record save." },
      { question: "Can I show errors on specific fields?", answer: "Yes. Set the error location to a field API name so the error appears inline on that field." },
      { question: "How do I bypass for integrations?", answer: "Use System.isBatch() or a Hierarchy Custom Setting flag in the formula for controlled bypass." },
    ],
  },
  {
    slug: "apex-test-generator",
    title: "Salesforce Apex Test Class Generator",
    shortDescription: "Generate Apex test class boilerplate with assertions and data factory stubs.",
    category: "salesforce",
    icon: "Code2",
    gradient: "from-violet-500 to-purple-600",
    badge: "Apex Dev",
    seo: {
      title: "Salesforce Apex Test Class Generator | Free Apex Helper | Ranburg",
      description:
        "Generate Apex test class templates with @isTest annotation, Test.startTest/stopTest, assertions, and mock data factory patterns for deployment coverage.",
      keywords: ["Apex test class generator", "Salesforce Apex helper", "Apex unit test template", "Salesforce test coverage"],
    },
    howToUse: [
      "Enter the Apex class name to test.",
      "Select methods to cover and assertion types.",
      "Choose data factory pattern: inline or @TestSetup.",
      "Copy generated test class into your Salesforce org.",
    ],
    formula: "Minimum 75% code coverage required for production deployments; aim for 90%+ with meaningful assertions.",
    faq: [
      { question: "What coverage is required?", answer: "Salesforce requires 75% Apex code coverage for production deployments. Each trigger must have coverage." },
      { question: "Should I use @TestSetup?", answer: "@TestSetup methods run once per test class and reduce DML. Use for shared test data across multiple test methods." },
      { question: "How do I mock callouts?", answer: "Implement HttpCalloutMock and Test.setMock(HttpCalloutMock.class, mock) before Test.startTest()." },
    ],
  },
  {
    slug: "flow-formula-builder",
    title: "Salesforce Flow Formula Builder",
    shortDescription: "Build formulas for Flow decision elements and formula resources.",
    category: "salesforce",
    icon: "Workflow",
    gradient: "from-orange-500 to-amber-600",
    badge: "Flow Tool",
    seo: {
      title: "Salesforce Flow Formula Builder | Free Flow Helper | Ranburg",
      description:
        "Build formulas for Salesforce Flow decisions, assignments, and formula resources. IF, ISBLANK, TEXT, and DATE functions with Flow-friendly syntax.",
      keywords: ["Salesforce Flow formula", "Flow formula builder", "Flow decision formula", "Salesforce Flow helper"],
    },
    howToUse: [
      "Select the Flow element type: Decision, Assignment, or Formula Resource.",
      "Pick a function template and enter resource API names.",
      "Preview the formula compatible with Flow formula editor.",
      "Copy into your Flow Builder formula field.",
    ],
    formula: "Flow formulas use {!$Record.Field} for record-triggered flows and {!varName} for variables.",
    faq: [
      { question: "How are Flow formulas different from field formulas?", answer: "Flow formulas reference Flow resources with {!syntax}, support collections, and can reference $Record in record-triggered flows." },
      { question: "Can I use formulas in Decision elements?", answer: "Yes. Decision outcomes use formula conditions. Each outcome evaluates a formula that returns TRUE or FALSE." },
      { question: "What about null handling?", answer: "Use ISBLANK(), BLANKVALUE(), and NULLVALUE() to handle nulls safely in Flow formulas." },
    ],
  },
  {
    slug: "date-formula-helper",
    title: "Salesforce Date Formula Helper",
    shortDescription: "Generate date and datetime formulas: TODAY, DATEVALUE, ADDMONTHS, and more.",
    category: "salesforce",
    icon: "Calendar",
    gradient: "from-pink-500 to-rose-600",
    badge: "Date Logic",
    seo: {
      title: "Salesforce Date Formula Helper | TODAY, ADDMONTHS | Ranburg",
      description:
        "Free Salesforce date formula helper. Generate TODAY(), DATEVALUE(), ADDMONTHS(), and business day calculations for formulas, flows, and validation rules.",
      keywords: ["Salesforce date formula", "TODAY formula Salesforce", "ADDMONTHS Salesforce", "date formula helper"],
    },
    howToUse: [
      "Choose a date operation: add days, add months, difference, or convert datetime.",
      "Enter field API names or literal dates.",
      "Preview the formula with correct Salesforce date functions.",
      "Copy into your formula field or validation rule.",
    ],
    formula: "ADDMONTHS(date, months) adds calendar months. TODAY() returns current date in org timezone.",
    faq: [
      { question: "How do timezones affect date formulas?", answer: "TODAY() and NOW() use the org default timezone. DateTime fields store UTC and display in user timezone." },
      { question: "How do I calculate business days?", answer: "Use CASE(MOD(startDate - DATE(1900,1,7), 7), ...) patterns or integrate with Business Hours API for complex logic." },
      { question: "Can I compare dates in validation rules?", answer: "Yes. Date comparisons use standard operators: CloseDate < TODAY() fires for overdue opportunities." },
    ],
  },
  {
    slug: "governor-limits-calculator",
    title: "Salesforce Governor Limits Calculator",
    shortDescription: "Estimate SOQL, DML, CPU, and heap usage for bulk Apex operations.",
    category: "salesforce",
    icon: "Gauge",
    gradient: "from-red-500 to-orange-600",
    badge: "Apex Limits",
    seo: {
      title: "Salesforce Governor Limits Calculator | Bulk Apex Planner | Ranburg",
      description:
        "Calculate Salesforce governor limit usage for bulk Apex. Plan SOQL queries, DML rows, CPU time, and heap size before deployment.",
      keywords: ["Salesforce governor limits", "Apex limits calculator", "SOQL limits", "bulk Apex calculator"],
    },
    howToUse: [
      "Enter batch size and number of SOQL queries per record.",
      "Add DML operations and estimated CPU time per iteration.",
      "Review limit usage against synchronous and async thresholds.",
      "Adjust batch size to stay within governor limits.",
    ],
    formula: "Synchronous: 100 SOQL, 150 DML, 10000ms CPU, 6MB heap. Async limits are higher.",
    faq: [
      { question: "What are the main governor limits?", answer: "Key limits: 100 SOQL queries, 150 DML statements, 50,000 DML rows, 10s CPU, 6MB heap (sync) per transaction." },
      { question: "When should I use batch Apex?", answer: "Use Batch Apex for processing 10,000+ records. Batch jobs have higher limits and run asynchronously." },
      { question: "How do I reduce SOQL in loops?", answer: "Query once outside the loop, store in a Map, and reference by Id inside the loop. Never SOQL inside for loops." },
    ],
  },
  {
    slug: "omnistudio-expression-builder",
    title: "OmniStudio Expression Builder",
    shortDescription: "Build OmniStudio DataRaptor and Integration Procedure expressions.",
    category: "salesforce",
    icon: "Layers",
    gradient: "from-indigo-500 to-blue-600",
    badge: "OmniStudio",
    popular: true,
    seo: {
      title: "OmniStudio Expression Builder | Free OmniStudio Tool | Ranburg",
      description:
        "Free OmniStudio expression builder for DataRaptor transforms, Integration Procedures, and OmniScripts. JSON path, merge field, and formula expressions.",
      keywords: ["OmniStudio expression builder", "OmniStudio consultant", "DataRaptor expression", "OmniStudio developer India"],
    },
    howToUse: [
      "Select expression context: DataRaptor, Integration Procedure, or OmniScript.",
      "Define input JSON path and target merge field.",
      "Add transformation logic: concat, format, conditional.",
      "Copy expression into your OmniStudio designer.",
    ],
    formula: "OmniStudio expressions use %fieldName% merge syntax and JSON path notation for nested data.",
    faq: [
      { question: "What is OmniStudio?", answer: "OmniStudio (formerly Vlocity) is Salesforce's industry cloud development framework for DataRaptors, Integration Procedures, and OmniScripts." },
      { question: "How do DataRaptor expressions work?", answer: "DataRaptor Extract/Transform/Load steps use formulas to map, filter, and transform JSON data between systems and Salesforce." },
      { question: "Do I need Industries Cloud for OmniStudio?", answer: "OmniStudio is available with Industries Cloud licenses and select Enterprise+ configurations." },
    ],
  },
  {
    slug: "revenue-cloud-pricing-calculator",
    title: "Revenue Cloud Pricing Calculator",
    shortDescription: "Model CPQ pricing: list price, discounts, quantity breaks, and net price.",
    category: "salesforce",
    icon: "DollarSign",
    gradient: "from-green-500 to-emerald-600",
    badge: "Revenue Cloud",
    popular: true,
    seo: {
      title: "Revenue Cloud Pricing Calculator | CPQ Price Estimator | Ranburg",
      description:
        "Free Revenue Cloud and CPQ pricing calculator. Model list price, volume discounts, partner margins, and net price for Salesforce quoting scenarios.",
      keywords: ["Revenue Cloud calculator", "Salesforce CPQ pricing", "Revenue Cloud consultant", "CPQ quote calculator"],
    },
    howToUse: [
      "Enter list price and quantity for the product line.",
      "Apply discount percentage or partner margin.",
      "Add volume break thresholds for tiered pricing.",
      "Review net price, total contract value, and annual recurring revenue.",
    ],
    formula: "Net Price = List Price × (1 - Discount%) × Quantity. TCV = Sum of all line net prices.",
    faq: [
      { question: "What is Revenue Cloud?", answer: "Salesforce Revenue Cloud combines CPQ, Billing, and Subscription Management for configure-price-quote-to-cash workflows." },
      { question: "How do volume discounts work in CPQ?", answer: "CPQ discount schedules apply tiered discounts based on quantity breaks defined in product rules." },
      { question: "Can this replace CPQ configuration?", answer: "This is an estimation tool for planning. Actual quotes require Salesforce CPQ or Revenue Cloud product configuration." },
    ],
  },
];
