/** Curated tool discovery — featured, popular, and recent slugs for /tools hub */
export const FEATURED_TOOL_SLUGS = [
  "jpg-to-png",
  "image-compressor",
  "pdf-merge",
  "keyword-density-checker",
  "youtube-tags-generator",
  "qr-code-generator",
  "profit-margin-calculator",
  "gst-calculator",
];

export const POPULAR_TOOL_SLUGS = [
  "jpg-to-png",
  "png-to-jpg",
  "image-compressor",
  "pdf-merge",
  "pdf-split",
  "meta-tag-generator",
  "word-counter",
  "slug-generator",
  "youtube-tags-generator",
  "instagram-hashtag-generator",
  "social-media-character-counter",
  "profit-margin-calculator",
  "roi-calculator",
  "password-generator",
  "qr-generator",
  "qr-code-generator",
  "json-formatter",
  "gst-calculator",
  "emi",
  "sip",
  "invoice-generator",
];

export const RECENT_TOOL_SLUGS = [
  "svg-to-png",
  "heic-to-jpg",
  "remove-exif",
  "pdf-page-remover",
  "pdf-to-jpg",
  "word-to-pdf",
  "schema-markup-generator",
  "open-graph-generator",
  "tiktok-earnings-calculator",
  "tiktok-engagement-calculator",
  "break-even-calculator",
  "invoice-generator",
  "loan-foreclosure-calculator",
  "youtube-revenue-calculator",
  "instagram-revenue-calculator",
];

export const SEARCH_SUGGESTIONS = [
  "Image",
  "PDF",
  "JPG to PNG",
  "Merge PDF",
  "YouTube",
  "Instagram",
  "TikTok",
  "SEO",
  "Meta tags",
  "Word counter",
  "QR Code",
  "GST",
  "ROI",
  "Calculator",
  "JSON",
  "Password",
];

export const SEARCH_TAGS = [
  { label: "Image", query: "image" },
  { label: "PDF", query: "pdf" },
  { label: "SEO", query: "seo" },
  { label: "YouTube", query: "youtube" },
  { label: "Instagram", query: "instagram" },
  { label: "TikTok", query: "tiktok" },
  { label: "Calculator", query: "calculator" },
  { label: "QR Code", query: "qr" },
  { label: "GST", query: "gst" },
  { label: "Merge", query: "merge" },
  { label: "Compress", query: "compress" },
  { label: "Salesforce", query: "salesforce" },
];
