import {
  TrendingUp,
  Wallet,
  Calculator,
  BarChart3,
  Tv,
  Braces,
  Database,
  FileCode,
  Linkedin,
  Type,
  AlignLeft,
  Sparkles,
  Image,
  Clock,
  FunctionSquare,
  Search,
  ShieldCheck,
  Workflow,
  Calendar,
  Gauge,
  Layers,
  DollarSign,
  Code2,
  Wrench,
  Regex,
  Fingerprint,
  KeyRound,
  Binary,
  FileText,
  QrCode,
  Ruler,
  Cake,
  CircleDollarSign,
  Percent,
  Youtube,
  Instagram,
  Bot,
  Map,
  Tags,
  Link,
  Link2,
  Hash,
  Heart,
  Share2,
  Crop,
  Minimize2,
  Maximize2,
  Files,
  SplitSquareHorizontal,
  FileOutput,
  FileX,
  FileType,
  FileImage,
  Smartphone,
  Shield,
  Scale,
  CreditCard,
  Home,
  Users,
  Moon,
  Palette,
  List,
  ImageDown,
  ImageUp,
  Music,
  Table,
  Sheet,
  ScanFace,
  Flame,
  GitCompare,
  Receipt,
  Award,
  Landmark,
  PiggyBank,
  ArrowUpDown,
  FileSearch,
  BookOpen,
  Video,
  Contact,
  PenLine,
  Eraser,
  Images,
  Globe,
  Banknote,
  Coins,
  Scissors,
  Aperture,
  Shrink,
  Monitor,
  UserRound,
  Stamp,
  ClipboardList,
  ListOrdered,
  ScanLine,
  Timer,
  FileSpreadsheet,
  Diff,
  Lock,
  Text,
  PenTool,
  BadgeDollarSign,
  Archive,
  Camera,
  GitMerge,
  IndianRupee,
  Building2,
  Contrast,
  Wand,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  TrendingUp,
  Wallet,
  Calculator,
  BarChart3,
  Tv,
  Braces,
  Database,
  FileCode,
  Linkedin,
  Type,
  AlignLeft,
  Sparkles,
  Image,
  Clock,
  FunctionSquare,
  Search,
  ShieldCheck,
  Workflow,
  Calendar,
  Gauge,
  Layers,
  DollarSign,
  Code2,
  Regex,
  Fingerprint,
  KeyRound,
  Binary,
  FileText,
  QrCode,
  Ruler,
  Cake,
  CircleDollarSign,
  Percent,
  Youtube,
  Instagram,
  Bot,
  Map,
  Tags,
  Link,
  Link2,
  Hash,
  Heart,
  Share2,
  Crop,
  Minimize2,
  Maximize2,
  Files,
  SplitSquareHorizontal,
  FileOutput,
  FileX,
  FileType,
  FileImage,
  Smartphone,
  Shield,
  Scale,
  CreditCard,
  Home,
  Users,
  Moon,
  Palette,
  List,
  ImageDown,
  ImageUp,
  Music,
  Table,
  Sheet,
  ScanFace,
  Flame,
  GitCompare,
  Receipt,
  Award,
  Landmark,
  PiggyBank,
  ArrowUpDown,
  FileSearch,
  BookOpen,
  Video,
  Contact,
  PenLine,
  Eraser,
  Images,
  Globe,
  Banknote,
  Coins,
  Scissors,
  Aperture,
  Shrink,
  Monitor,
  UserRound,
  Stamp,
  ClipboardList,
  ListOrdered,
  ScanLine,
  Timer,
  FileSpreadsheet,
  Diff,
  Lock,
  Text,
  PenTool,
  BadgeDollarSign,
  Archive,
  Camera,
  GitMerge,
  IndianRupee,
  Building2,
  Contrast,
  Wand,
};

/** Per-slug icons so cards never fall back to a generic wrench / leftover glyph. */
const SLUG_ICONS: Record<string, string> = {
  sip: "TrendingUp",
  swp: "Wallet",
  emi: "Calculator",
  "ltv-cac": "BarChart3",
  "twitch-sub-revenue": "Tv",
  "json-formatter": "Braces",
  "sql-formatter": "Database",
  minifier: "FileCode",
  "linkedin-formatter": "Linkedin",
  "case-converter": "Type",
  "lorem-ipsum": "AlignLeft",
  "glassmorphism-generator": "Layers",
  "image-converter": "Images",
  "regex-tester": "Regex",
  "uuid-generator": "Fingerprint",
  "password-generator": "Lock",
  "base64-encoder": "Binary",
  "pdf-tools": "Files",
  "qr-generator": "QrCode",
  "qr-code-generator": "QrCode",
  "unit-converter": "Ruler",
  "age-calculator": "Cake",
  "currency-converter": "CircleDollarSign",
  "gst-calculator": "Percent",
  "youtube-channel-insights": "Youtube",
  "instagram-profile-insights": "Instagram",
  "youtube-revenue-calculator": "BadgeDollarSign",
  "instagram-revenue-calculator": "BadgeDollarSign",
  "adsense-revenue-calculator": "Coins",
  "invoice-generator": "Receipt",
  "loan-foreclosure-calculator": "Banknote",

  "jpg-to-png": "FileImage",
  "png-to-jpg": "Image",
  "webp-to-png": "ImageDown",
  "png-to-webp": "ImageUp",
  "image-compressor": "Shrink",
  "image-resizer": "Maximize2",
  "crop-image": "Crop",
  "image-to-base64": "Binary",
  "base64-to-image": "FileImage",
  "remove-exif": "Camera",
  "heic-to-jpg": "Smartphone",
  "svg-to-png": "PenTool",
  "color-background-remover": "Eraser",
  "avif-to-jpg": "ImageDown",
  "jpg-to-avif": "ImageUp",
  "compress-to-exact-size": "Archive",
  "face-blur": "ScanFace",

  "pdf-merge": "GitMerge",
  "pdf-split": "Scissors",
  "pdf-compressor": "Archive",
  "pdf-to-jpg": "FileImage",
  "jpg-to-pdf": "Images",
  "word-to-pdf": "FileType",
  "pdf-page-extractor": "FileOutput",
  "pdf-page-remover": "FileX",
  "pdf-page-reorder": "ArrowUpDown",
  "pdf-to-text": "FileSearch",
  "pdf-signer": "Stamp",

  "keyword-density-checker": "BarChart3",
  "meta-tag-generator": "Tags",
  "robots-txt-generator": "Bot",
  "xml-sitemap-generator": "Globe",
  "open-graph-generator": "Share2",
  "schema-markup-generator": "Braces",
  "url-encoder-decoder": "Link",
  "word-counter": "Hash",
  "slug-generator": "Link2",
  "ai-crawler-robots-checker": "Bot",
  "llms-txt-generator": "FileText",

  "youtube-tags-generator": "Tags",
  "youtube-description-generator": "ClipboardList",
  "youtube-hashtag-generator": "Hash",
  "instagram-hashtag-generator": "Hash",
  "instagram-engagement-calculator": "Heart",
  "tiktok-engagement-calculator": "Video",
  "tiktok-earnings-calculator": "Coins",
  "social-media-character-counter": "Text",
  "safe-zone-checker": "Aperture",
  "youtube-thumbnail-checker": "Youtube",
  "social-image-size-checker": "Images",
  "youtube-chapter-generator": "ListOrdered",

  "profit-margin-calculator": "Percent",
  "roi-calculator": "TrendingUp",
  "break-even-calculator": "Scale",
  "burn-rate-runway-calculator": "Flame",
  "freelancer-hourly-rate-calculator": "Timer",
  "ab-test-significance-calculator": "GitCompare",

  "credit-card-finder": "CreditCard",
  "rent-vs-buy-calculator": "Home",
  "bill-split-calculator": "Users",
  "compound-interest-calculator": "TrendingUp",
  "sleep-calculator": "Moon",
  "salary-hike-calculator": "IndianRupee",
  "color-contrast-checker": "Contrast",
  "apex-trigger-generator": "Code2",
  "dataraptor-formula-builder": "Layers",
  "sharing-rule-generator": "ShieldCheck",
  "formula-explainer": "Wand",

  "ctc-in-hand-calculator": "Wallet",
  "tds-calculator": "Receipt",
  "hra-exemption-calculator": "Building2",
  "gratuity-calculator": "Award",
  "hsn-sac-finder": "ScanLine",
  "ifsc-finder": "Landmark",
  "lic-maturity-calculator": "ShieldCheck",
  "pf-calculator": "PiggyBank",
  "ppf-calculator": "Landmark",
  "home-loan-vs-mutual-fund": "Scale",

  "csv-to-json": "Braces",
  "json-to-csv": "Table",
  "excel-to-csv": "FileSpreadsheet",
  "opus-to-mp3": "Music",
  "text-diff-checker": "Diff",
  "markdown-preview": "BookOpen",
  "screen-recorder": "Monitor",
  "resume-builder": "UserRound",
  "jwt-decoder": "KeyRound",
  "percentage-calculator": "Percent",
  "percentage-change-calculator": "TrendingUp",
  "bmi-calculator": "Gauge",
  "cagr-calculator": "TrendingUp",
  "fd-calculator": "PiggyBank",
  "simple-interest-calculator": "Percent",
  "vat-calculator": "Receipt",
  "unix-timestamp-converter": "Clock",
  "utm-builder": "Link2",
  "sha256-hash-generator": "Lock",
  "color-converter": "Palette",
  "working-days-calculator": "Calendar",
  "number-to-words": "Type",
  "html-encoder": "Code2",
  "aspect-ratio-calculator": "Maximize2",
  "duplicate-line-remover": "List",
  "find-and-replace": "Search",
  "hours-calculator": "Timer",
  "readability-checker": "BookOpen",
  "random-number-generator": "Hash",
  "discount-calculator": "Percent",
  "rd-calculator": "PiggyBank",
  "inflation-calculator": "TrendingUp",
  "calorie-calculator": "Flame",
  "password-strength-checker": "ShieldCheck",
  "date-difference-calculator": "Calendar",
  "roman-numeral-converter": "Type",
  "text-to-binary": "Binary",
  "tip-calculator": "Receipt",
  "average-calculator": "Calculator",
  "px-to-rem-converter": "Ruler",
  "water-intake-calculator": "Gauge",

  "cron-generator": "Clock",
  "formula-generator": "FunctionSquare",
  "soql-builder": "Search",
  "validation-rule-generator": "ShieldCheck",
  "apex-test-generator": "Code2",
  "flow-formula-builder": "Workflow",
  "date-formula-helper": "Calendar",
  "governor-limits-calculator": "Gauge",
  "omnistudio-expression-builder": "Layers",
  "revenue-cloud-pricing-calculator": "DollarSign",
};

export function getToolIcon(name: string, slug?: string): LucideIcon {
  if (slug && SLUG_ICONS[slug]) {
    return ICON_MAP[SLUG_ICONS[slug]] ?? ICON_MAP[name] ?? Wrench;
  }
  return ICON_MAP[name] ?? Wrench;
}
