/** Curated tool discovery — featured, popular, and recent slugs for /tools hub.
 * Prefer PRIORITY_INDEX_TOOL_SLUGS (seoGrowthConfig) so internal PageRank hits money pages.
 */
export const FEATURED_TOOL_SLUGS = [
  "home-loan-vs-mutual-fund",
  "ctc-in-hand-calculator",
  "invoice-generator",
  "emi",
  "sip",
  "gst-calculator",
  "json-formatter",
  "pdf-merge",
];

export const POPULAR_TOOL_SLUGS = [
  "home-loan-vs-mutual-fund",
  "emi",
  "sip",
  "gst-calculator",
  "loan-foreclosure-calculator",
  "youtube-revenue-calculator",
  "youtube-channel-insights",
  "instagram-revenue-calculator",
  "instagram-profile-insights",
  "adsense-revenue-calculator",
  "youtube-hashtag-generator",
  "instagram-hashtag-generator",
  "youtube-tags-generator",
  "jpg-to-png",
  "image-compressor",
  "pdf-merge",
  "heic-to-jpg",
  "json-formatter",
  "password-generator",
  "qr-generator",
  "currency-converter",
];

export const RECENT_TOOL_SLUGS = [
  "home-loan-vs-mutual-fund",
  "lic-maturity-calculator",
  "pf-calculator",
  "swp",
  "ctc-in-hand-calculator",
  "invoice-generator",
  "safe-zone-checker",
  "youtube-thumbnail-checker",
  "compress-to-exact-size",
  "burn-rate-runway-calculator",
  "opus-to-mp3",
  "invoice-generator",
  "ctc-in-hand-calculator",
  "text-diff-checker",
  "markdown-preview",
  "resume-builder",
  "ppf-calculator",
];

export const SEARCH_SUGGESTIONS = [
  "Home loan vs SIP",
  "CTC to in-hand",
  "Invoice",
  "EMI",
  "SIP",
  "GST",
  "Safe zone",
  "YouTube thumbnail",
  "YouTube revenue",
  "Opus to MP3",
  "JWT decoder",
  "Burn rate",
  "HSN",
  "IFSC",
  "CSV to JSON",
];

export const SEARCH_TAGS = [
  { label: "Home vs SIP", query: "home loan" },
  { label: "EMI", query: "emi" },
  { label: "SIP", query: "sip" },
  { label: "GST", query: "gst" },
  { label: "YouTube", query: "youtube" },
  { label: "Instagram", query: "instagram" },
  { label: "Image", query: "image" },
  { label: "PDF", query: "pdf" },
  { label: "HEIC", query: "heic" },
  { label: "SEO", query: "seo" },
  { label: "Calculator", query: "calculator" },
  { label: "QR Code", query: "qr" },
  { label: "Salesforce", query: "salesforce" },
];
