import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const faq = [
  { question: "Is this tool free?", answer: "Yes. All Ranburg tools are free with no account required." },
  { question: "Do you store my inputs?", answer: "No. Calculations run in your browser and are not uploaded." },
  { question: "Can I use results commercially?", answer: "Yes. Outputs are yours. Confirm financial or medical decisions with a professional." },
];

export const DEMAND_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    shortDescription: "Find X% of a number, what percent X is of Y, and percentage change — instantly.",
    category: "financial",
    icon: "Percent",
    gradient: "from-emerald-500 to-teal-600",
    badge: "Everyday Math",
    popular: true,
    keywords: ["percentage calculator", "percent of a number", "percentage calculator online", "what percent is"],
    howToUse: ["Enter the percent and the base value.", "Or enter two numbers to see what percent one is of the other.", "Copy the result."],
    formula: "X% of Y = (X/100)×Y. Part/whole × 100 = percent.",
    faq,
    seoTitle: "Percentage Calculator Online Free | Ranburg",
    seoDescription: "Free percentage calculator: what is X% of Y, X is what percent of Y, and percent change. Instant, no signup.",
  }),
  makeTool({
    slug: "percentage-change-calculator",
    title: "Percentage Increase Calculator",
    shortDescription: "Calculate percentage increase or decrease from an old value to a new value.",
    category: "financial",
    icon: "TrendingUp",
    gradient: "from-teal-500 to-cyan-600",
    badge: "Everyday Math",
    popular: true,
    keywords: ["percentage increase calculator", "percent decrease calculator", "percentage change", "percent difference"],
    howToUse: ["Enter the original value.", "Enter the new value.", "Read the % increase or decrease."],
    formula: "Change % = ((new − old) / |old|) × 100",
    faq,
    seoTitle: "Percentage Increase & Decrease Calculator | Ranburg",
    seoDescription: "Free percentage increase calculator. See percent up or down between two numbers. No signup.",
  }),
  makeTool({
    slug: "bmi-calculator",
    title: "BMI Calculator",
    shortDescription: "Calculate Body Mass Index from height and weight with WHO category.",
    category: "financial",
    icon: "Gauge",
    gradient: "from-sky-500 to-blue-600",
    badge: "Health",
    popular: true,
    keywords: ["bmi calculator", "bmi calculator online", "body mass index calculator", "bmi chart"],
    howToUse: ["Enter weight in kg.", "Enter height in cm.", "See BMI and category."],
    formula: "BMI = kg / (height in metres)²",
    faq: [
      ...faq,
      { question: "Is BMI a diagnosis?", answer: "No. BMI is a screening number. Muscle mass, age, and health conditions matter — ask a clinician." },
    ],
    seoTitle: "BMI Calculator Online Free (kg/cm) | Ranburg",
    seoDescription: "Free BMI calculator: enter height and weight for Body Mass Index and WHO category. Instant, private, no signup.",
  }),
  makeTool({
    slug: "cagr-calculator",
    title: "CAGR Calculator",
    shortDescription:
      "Compute CAGR from start and end values, plus indicative 10-year housing CAGRs for 20 Indian cities, 20 US metros, Singapore, and more.",
    category: "financial",
    icon: "TrendingUp",
    gradient: "from-indigo-500 to-violet-600",
    badge: "Investing",
    popular: true,
    keywords: [
      "cagr calculator",
      "cagr calculator online",
      "compound annual growth rate",
      "cagr formula",
      "property CAGR India",
      "city housing CAGR",
    ],
    howToUse: [
      "Enter starting value, ending value, and years.",
      "Read CAGR as a percent.",
      "Use the city table for 10-year housing price CAGRs, then compare buy vs SIP on the housing tools.",
    ],
    formula: "CAGR = (end/start)^(1/years) − 1",
    faq,
    seoTitle: "CAGR Calculator Online Free | Ranburg",
    seoDescription:
      "Free CAGR calculator plus 10-year housing CAGRs for Indian cities, US metros, Singapore, and other markets. No signup.",
  }),
  makeTool({
    slug: "fd-calculator",
    title: "FD Calculator",
    shortDescription: "Estimate fixed deposit maturity amount with compounding for Indian bank FDs.",
    category: "financial",
    icon: "PiggyBank",
    gradient: "from-amber-500 to-orange-600",
    badge: "India Finance",
    popular: true,
    keywords: ["fd calculator", "fixed deposit calculator", "fd calculator india", "fd maturity calculator"],
    howToUse: ["Enter principal, interest rate, and tenure.", "Choose compounding frequency.", "See maturity value and interest earned."],
    formula: "A = P(1 + r/n)^(n×t)",
    faq,
    seoTitle: "FD Calculator India — Maturity Amount | Ranburg",
    seoDescription: "Free FD calculator: estimate fixed deposit maturity and interest with quarterly compounding. No signup.",
  }),
  makeTool({
    slug: "simple-interest-calculator",
    title: "Simple Interest Calculator",
    shortDescription: "Calculate simple interest and total amount from principal, rate, and time.",
    category: "financial",
    icon: "Percent",
    gradient: "from-lime-500 to-green-600",
    badge: "Everyday Math",
    keywords: ["simple interest calculator", "simple interest formula", "si calculator"],
    howToUse: ["Enter principal, annual rate, and years.", "See interest and total payable."],
    formula: "SI = (P × R × T) / 100",
    faq,
    seoTitle: "Simple Interest Calculator Online Free | Ranburg",
    seoDescription: "Free simple interest calculator. SI = PRT/100 with total amount. Instant, no signup.",
  }),
  makeTool({
    slug: "vat-calculator",
    title: "VAT Calculator",
    shortDescription: "Add or remove VAT/GST-style tax from a net or gross amount.",
    category: "financial",
    icon: "Receipt",
    gradient: "from-orange-500 to-red-500",
    badge: "Tax",
    keywords: ["vat calculator", "vat calculator online", "add vat", "remove vat"],
    howToUse: ["Enter net or gross amount.", "Set VAT rate.", "See tax and the other total."],
    formula: "Gross = net × (1 + rate). Net = gross / (1 + rate).",
    faq,
    seoTitle: "VAT Calculator Online Free — Add or Remove VAT | Ranburg",
    seoDescription: "Free VAT calculator: add or strip VAT at any rate. Useful for invoices and EU/UK quotes.",
  }),
  makeTool({
    slug: "unix-timestamp-converter",
    title: "Unix Timestamp Converter",
    shortDescription: "Convert epoch seconds to local/UTC time and datetime back to Unix time.",
    category: "developer",
    icon: "Clock",
    gradient: "from-slate-600 to-zinc-700",
    badge: "Developer",
    popular: true,
    keywords: ["unix timestamp converter", "epoch converter", "unix time converter", "epoch to date"],
    howToUse: ["Paste a Unix timestamp in seconds.", "Or pick a date and time.", "Copy UTC, local, and ISO strings."],
    formula: "Unix time = seconds since 1970-01-01T00:00:00Z",
    faq,
    seoTitle: "Unix Timestamp Converter (Epoch) Free | Ranburg",
    seoDescription: "Free epoch converter: Unix timestamp to date and datetime to Unix. UTC and local time. No signup.",
  }),
  makeTool({
    slug: "utm-builder",
    title: "UTM Link Builder",
    shortDescription: "Build campaign URLs with utm_source, utm_medium, and utm_campaign.",
    category: "productivity",
    icon: "Link2",
    gradient: "from-blue-500 to-indigo-600",
    badge: "Marketing",
    popular: true,
    keywords: ["utm builder", "utm link builder", "utm generator", "campaign url builder"],
    howToUse: ["Paste the landing page URL.", "Add source, medium, and campaign.", "Copy the tagged link."],
    formula: "url + utm_source + utm_medium + utm_campaign query params",
    faq,
    seoTitle: "UTM Builder — Campaign URL Generator Free | Ranburg",
    seoDescription: "Free UTM builder for Google Analytics campaign links. Add source, medium, campaign and copy.",
  }),
  makeTool({
    slug: "sha256-hash-generator",
    title: "SHA-256 Hash Generator",
    shortDescription: "Generate a SHA-256 hash of any text in your browser with Web Crypto.",
    category: "developer",
    icon: "Lock",
    gradient: "from-neutral-700 to-stone-800",
    badge: "Security",
    keywords: ["sha256 hash", "sha256 generator", "hash generator online", "sha 256 hash generator"],
    howToUse: ["Paste text.", "Hash with SHA-256 in the browser.", "Copy the hex digest."],
    formula: "SHA-256 via Web Crypto SubtleCrypto.digest",
    faq,
    seoTitle: "SHA-256 Hash Generator Online Free | Ranburg",
    seoDescription: "Free SHA-256 hash generator. Hash text locally in your browser — nothing is uploaded.",
  }),
  makeTool({
    slug: "color-converter",
    title: "HEX to RGB Converter",
    shortDescription: "Convert HEX colors to RGB and RGB back to HEX for CSS and design.",
    category: "design",
    icon: "Palette",
    gradient: "from-fuchsia-500 to-pink-600",
    badge: "Design",
    keywords: ["hex to rgb", "rgb to hex", "color converter", "hex color converter"],
    howToUse: ["Enter a HEX code like #0D9B8A.", "Read RGB values.", "Or type R,G,B and get HEX."],
    formula: "HEX pairs → 0–255 RGB channels",
    faq,
    seoTitle: "HEX to RGB Converter Online Free | Ranburg",
    seoDescription: "Free HEX to RGB and RGB to HEX color converter for CSS. Instant, no signup.",
  }),
  makeTool({
    slug: "working-days-calculator",
    title: "Working Days Calculator",
    shortDescription: "Count business days between two dates, excluding Saturday and Sunday.",
    category: "productivity",
    icon: "Calendar",
    gradient: "from-cyan-500 to-blue-600",
    badge: "HR",
    popular: true,
    keywords: ["working days calculator", "business days calculator", "weekdays between dates", "network days"],
    howToUse: ["Pick a start date.", "Pick an end date.", "See weekday count (Sat/Sun excluded)."],
    formula: "Inclusive count of dates where weekday is Mon–Fri",
    faq,
    seoTitle: "Working Days Calculator — Business Days | Ranburg",
    seoDescription: "Free working days calculator. Count weekdays between two dates. No signup.",
  }),
  makeTool({
    slug: "number-to-words",
    title: "Number to Words Converter",
    shortDescription: "Convert numbers to Indian numbering words (crore, lakh) for cheques and invoices.",
    category: "financial",
    icon: "Type",
    gradient: "from-violet-500 to-purple-600",
    badge: "India",
    popular: true,
    keywords: ["number to words", "number to words converter", "amount in words", "cheque amount in words"],
    howToUse: ["Enter an amount.", "Copy Indian-style words (lakh/crore).", "Paste into invoices or cheques."],
    formula: "Indian grouping: crore, lakh, thousand, remainder",
    faq,
    seoTitle: "Number to Words Converter (Indian) Free | Ranburg",
    seoDescription: "Free number to words converter for Indian rupees — lakh and crore. Amount in words for invoices.",
  }),
  makeTool({
    slug: "html-encoder",
    title: "HTML Encoder Decoder",
    shortDescription: "Escape and unescape HTML entities for snippets, blogs, and CMS paste.",
    category: "developer",
    icon: "Code2",
    gradient: "from-sky-600 to-blue-700",
    badge: "Developer",
    keywords: ["html encoder", "html encoder decoder", "html escape", "html entities encoder"],
    howToUse: ["Paste HTML or text.", "Encode to entities or decode back.", "Copy the output."],
    formula: "& < > \" ' → HTML entities",
    faq,
    seoTitle: "HTML Encoder / Decoder Online Free | Ranburg",
    seoDescription: "Free HTML encoder and decoder. Escape entities in your browser — no signup.",
  }),
  makeTool({
    slug: "aspect-ratio-calculator",
    title: "Aspect Ratio Calculator",
    shortDescription: "Simplify width × height to a ratio like 16:9 and scale to a target width.",
    category: "design",
    icon: "Maximize2",
    gradient: "from-rose-500 to-orange-500",
    badge: "Creator",
    keywords: ["aspect ratio calculator", "16:9 calculator", "aspect ratio from resolution", "ratio calculator"],
    howToUse: ["Enter width and height.", "See simplified ratio.", "Optionally scale to a new width."],
    formula: "ratio = width/height reduced by GCD",
    faq,
    seoTitle: "Aspect Ratio Calculator (16:9, 9:16) Free | Ranburg",
    seoDescription: "Free aspect ratio calculator for 16:9, 9:16, and any resolution. Scale height from width.",
  }),
  makeTool({
    slug: "duplicate-line-remover",
    title: "Duplicate Line Remover",
    shortDescription: "Remove duplicate lines from a list while keeping original order.",
    category: "productivity",
    icon: "List",
    gradient: "from-emerald-600 to-teal-500",
    badge: "Text",
    keywords: ["remove duplicate lines", "duplicate line remover", "unique lines online", "dedupe text"],
    howToUse: ["Paste a list.", "Remove exact duplicate lines.", "Copy the unique list."],
    formula: "First-seen line kept; later exact matches dropped",
    faq,
    seoTitle: "Remove Duplicate Lines Online Free | Ranburg",
    seoDescription: "Free duplicate line remover. Dedupe lists in your browser. Keep first occurrence. No signup.",
  }),
  makeTool({
    slug: "find-and-replace",
    title: "Find and Replace Text",
    shortDescription: "Find and replace text in the browser, with optional case-sensitive matching.",
    category: "productivity",
    icon: "Search",
    gradient: "from-indigo-500 to-blue-600",
    badge: "Text",
    keywords: ["find and replace online", "find replace text", "replace all online"],
    howToUse: ["Paste your text.", "Enter find and replace strings.", "Replace all and copy."],
    formula: "Global string split/join (optional case-insensitive)",
    faq,
    seoTitle: "Find and Replace Text Online Free | Ranburg",
    seoDescription: "Free find and replace tool. Replace all matches in your browser. No signup.",
  }),
  makeTool({
    slug: "hours-calculator",
    title: "Hours Calculator",
    shortDescription: "Calculate hours and minutes between two times — useful for timesheets.",
    category: "productivity",
    icon: "Timer",
    gradient: "from-amber-500 to-yellow-500",
    badge: "HR",
    keywords: ["hours calculator", "time duration calculator", "hours between times", "timesheet calculator"],
    howToUse: ["Enter start time.", "Enter end time.", "See duration in hours and minutes."],
    formula: "Minutes elapsed; wrap past midnight",
    faq,
    seoTitle: "Hours Calculator — Time Between Two Times | Ranburg",
    seoDescription: "Free hours calculator for timesheets. Duration between two clock times, including overnight.",
  }),
  makeTool({
    slug: "readability-checker",
    title: "Readability Checker",
    shortDescription: "Estimate Flesch Reading Ease, word count, and sentence count for your copy.",
    category: "productivity",
    icon: "BookOpen",
    gradient: "from-teal-500 to-emerald-600",
    badge: "SEO Writing",
    keywords: ["readability checker", "flesch reading ease", "readability score", "reading level checker"],
    howToUse: ["Paste an article or paragraph.", "See Flesch score, words, and sentences.", "Aim for 60+ for general web copy."],
    formula: "Flesch = 206.835 − 1.015(words/sentences) − 84.6(syllables/words)",
    faq,
    seoTitle: "Readability Checker (Flesch) Online Free | Ranburg",
    seoDescription: "Free readability checker with Flesch Reading Ease. Check web copy in your browser.",
  }),
  makeTool({
    slug: "random-number-generator",
    title: "Random Number Generator",
    shortDescription: "Generate random integers in a range — for giveaways, samples, and testing.",
    category: "developer",
    icon: "Hash",
    gradient: "from-slate-500 to-slate-700",
    badge: "Utility",
    keywords: ["random number generator", "random number picker", "rng online", "random integer generator"],
    howToUse: ["Set min and max.", "Generate one or many numbers.", "Copy the result."],
    formula: "Inclusive integer via crypto.getRandomValues when available",
    faq,
    seoTitle: "Random Number Generator Online Free | Ranburg",
    seoDescription: "Free random number generator. Pick integers in a range in your browser.",
  }),
  makeTool({
    slug: "discount-calculator",
    title: "Discount Calculator",
    shortDescription: "Find sale price and amount saved from an original price and discount percent.",
    category: "financial",
    icon: "Percent",
    gradient: "from-rose-500 to-red-600",
    badge: "Shopping",
    popular: true,
    keywords: ["discount calculator", "sale price calculator", "percent off calculator", "discount calculator online"],
    howToUse: ["Enter the original price.", "Enter the discount percent.", "See savings and the final price."],
    formula: "Final = original × (1 − discount%)",
    faq,
    seoTitle: "Discount Calculator — Sale Price Online Free | Ranburg",
    seoDescription: "Free discount calculator: percent off, amount saved, and sale price. Instant, no signup.",
  }),
  makeTool({
    slug: "rd-calculator",
    title: "RD Calculator",
    shortDescription: "Estimate recurring deposit maturity for monthly RD deposits in India.",
    category: "financial",
    icon: "PiggyBank",
    gradient: "from-amber-600 to-yellow-600",
    badge: "India Finance",
    popular: true,
    keywords: ["rd calculator", "recurring deposit calculator", "rd calculator india", "rd maturity calculator"],
    howToUse: ["Enter monthly deposit, interest rate, and months.", "See estimated maturity and interest."],
    formula: "Quarterly compounding RD: P × [(1+i)^n − 1] / [1 − (1+i)^(−1/3)]",
    faq,
    seoTitle: "RD Calculator India — Recurring Deposit | Ranburg",
    seoDescription: "Free RD calculator for India. Estimate recurring deposit maturity from monthly deposits.",
  }),
  makeTool({
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    shortDescription: "See what an amount grows to after years of inflation, or the future cost of goods.",
    category: "financial",
    icon: "TrendingUp",
    gradient: "from-orange-500 to-amber-600",
    badge: "Planning",
    keywords: ["inflation calculator", "inflation calculator india", "future value inflation", "purchasing power calculator"],
    howToUse: ["Enter today’s amount.", "Set inflation rate and years.", "Read the inflated future value."],
    formula: "Future = amount × (1 + rate)^years",
    faq,
    seoTitle: "Inflation Calculator Online Free | Ranburg",
    seoDescription: "Free inflation calculator: future cost of money after years of inflation. No signup.",
  }),
  makeTool({
    slug: "calorie-calculator",
    title: "Calorie Calculator",
    shortDescription: "Estimate BMR and daily calories (TDEE) from height, weight, age, and activity.",
    category: "financial",
    icon: "Flame",
    gradient: "from-red-500 to-orange-500",
    badge: "Health",
    popular: true,
    keywords: ["calorie calculator", "tdee calculator", "bmr calculator", "calorie calculator online"],
    howToUse: ["Enter weight, height, age, and sex.", "Pick activity level.", "See BMR and daily calorie estimate."],
    formula: "Mifflin–St Jeor BMR × activity factor",
    faq: [
      ...faq,
      { question: "Is this medical advice?", answer: "No. Calorie needs vary. Use this as a planning estimate and talk to a clinician for health goals." },
    ],
    seoTitle: "Calorie Calculator (BMR & TDEE) Free | Ranburg",
    seoDescription: "Free calorie calculator: Mifflin–St Jeor BMR and TDEE from activity. Instant, private, no signup.",
  }),
  makeTool({
    slug: "password-strength-checker",
    title: "Password Strength Checker",
    shortDescription: "Score a password locally for length, mixed case, digits, and symbols. Nothing is sent.",
    category: "developer",
    icon: "ShieldCheck",
    gradient: "from-slate-700 to-emerald-700",
    badge: "Security",
    popular: true,
    keywords: ["password strength checker", "password checker", "how strong is my password", "password strength test"],
    howToUse: ["Type or paste a password.", "Read the strength score.", "Generate a stronger one with our password generator."],
    formula: "Heuristic score from length and character classes (checked in-browser)",
    faq,
    seoTitle: "Password Strength Checker Online Free | Ranburg",
    seoDescription: "Free password strength checker. Test locally in your browser — we do not upload your password.",
  }),
  makeTool({
    slug: "date-difference-calculator",
    title: "Date Difference Calculator",
    shortDescription: "Count calendar days between two dates for deadlines, invoices, and travel.",
    category: "productivity",
    icon: "Calendar",
    gradient: "from-sky-500 to-cyan-600",
    badge: "Everyday",
    popular: true,
    keywords: ["date difference calculator", "days between dates", "how many days between two dates", "date duration calculator"],
    howToUse: ["Pick a start date.", "Pick an end date.", "See the number of calendar days."],
    formula: "Round((end − start) / 86,400,000 ms)",
    faq,
    seoTitle: "Days Between Dates Calculator Free | Ranburg",
    seoDescription: "Free date difference calculator. How many days between two dates — instant, no signup.",
  }),
  makeTool({
    slug: "roman-numeral-converter",
    title: "Roman Numeral Converter",
    shortDescription: "Convert numbers to Roman numerals and Roman numerals back to numbers (I–MMM).",
    category: "productivity",
    icon: "Type",
    gradient: "from-stone-500 to-neutral-700",
    badge: "Reference",
    keywords: ["roman numeral converter", "roman numerals converter", "number to roman numerals", "roman to number"],
    howToUse: ["Enter a number 1–3999.", "Copy the Roman numeral.", "Or paste Roman text to decode."],
    formula: "Standard subtractive notation (IV, IX, XL, XC, CD, CM)",
    faq,
    seoTitle: "Roman Numeral Converter Online Free | Ranburg",
    seoDescription: "Free Roman numeral converter. Number to Roman and back. Instant, no signup.",
  }),
  makeTool({
    slug: "text-to-binary",
    title: "Text to Binary Converter",
    shortDescription: "Convert text to 8-bit binary and binary back to text in your browser.",
    category: "developer",
    icon: "Binary",
    gradient: "from-indigo-600 to-slate-800",
    badge: "Developer",
    keywords: ["text to binary", "binary translator", "text to binary converter", "binary to text"],
    howToUse: ["Paste text.", "Copy 8-bit binary.", "Or paste binary to decode."],
    formula: "Each character → 8-bit UTF-16 code unit as binary",
    faq,
    seoTitle: "Text to Binary Converter Online Free | Ranburg",
    seoDescription: "Free text to binary and binary to text converter. Runs locally. No signup.",
  }),
  makeTool({
    slug: "tip-calculator",
    title: "Tip Calculator",
    shortDescription: "Split a bill with a tip percent across any number of people.",
    category: "financial",
    icon: "Receipt",
    gradient: "from-emerald-500 to-lime-600",
    badge: "Everyday",
    keywords: ["tip calculator", "tip calculator split", "gratuity calculator", "bill tip calculator"],
    howToUse: ["Enter the bill.", "Set tip percent and people.", "See tip, total, and per person."],
    formula: "Tip = bill × percent; each = (bill + tip) / people",
    faq,
    seoTitle: "Tip Calculator — Split Bill Online Free | Ranburg",
    seoDescription: "Free tip calculator with split. Tip amount, total, and per-person share. No signup.",
  }),
  makeTool({
    slug: "average-calculator",
    title: "Average Calculator",
    shortDescription: "Calculate the mean of a list of numbers — grades, scores, or metrics.",
    category: "financial",
    icon: "Calculator",
    gradient: "from-cyan-600 to-blue-700",
    badge: "Everyday Math",
    keywords: ["average calculator", "mean calculator", "average of numbers", "calculate average online"],
    howToUse: ["Paste numbers separated by commas or new lines.", "See the arithmetic mean."],
    formula: "Mean = sum / count",
    faq,
    seoTitle: "Average Calculator Online Free | Ranburg",
    seoDescription: "Free average calculator. Mean of a list of numbers. Instant, no signup.",
  }),
  makeTool({
    slug: "px-to-rem-converter",
    title: "PX to REM Converter",
    shortDescription: "Convert CSS pixels to rem (and rem to px) with a custom root font size.",
    category: "developer",
    icon: "Ruler",
    gradient: "from-violet-500 to-fuchsia-600",
    badge: "CSS",
    keywords: ["px to rem", "px to rem converter", "rem to px", "css rem calculator"],
    howToUse: ["Enter px.", "Set root font size (usually 16).", "Copy rem."],
    formula: "rem = px / root; px = rem × root",
    faq,
    seoTitle: "PX to REM Converter (CSS) Free | Ranburg",
    seoDescription: "Free PX to REM converter for CSS. Change root size. Instant, no signup.",
  }),
  makeTool({
    slug: "water-intake-calculator",
    title: "Water Intake Calculator",
    shortDescription: "Estimate daily water need from body weight (about 33 ml per kg).",
    category: "financial",
    icon: "Gauge",
    gradient: "from-sky-400 to-blue-600",
    badge: "Health",
    keywords: ["water intake calculator", "how much water should I drink", "daily water intake calculator"],
    howToUse: ["Enter body weight in kg.", "See litres and millilitres per day."],
    formula: "litres ≈ weight(kg) × 0.033",
    faq: [
      ...faq,
      { question: "Is this a medical recommendation?", answer: "No. Climate, exercise, and health conditions change needs. This is a simple planning estimate." },
    ],
    seoTitle: "Water Intake Calculator Online Free | Ranburg",
    seoDescription: "Free water intake calculator from body weight. Estimate daily litres. Not medical advice.",
  }),
];
