import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const privacyFaq = [
  { question: "Are my images uploaded to a server?", answer: "No. All image processing runs locally in your browser. Files never leave your device." },
  { question: "What image formats are supported?", answer: "Most tools accept PNG, JPG, WebP, and GIF. HEIC conversion requires a supported browser." },
  { question: "Is this tool free?", answer: "Yes. Ranburg image tools are free with no signup." },
];

export const IMAGE_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "jpg-to-png",
    title: "JPG to PNG Converter",
    shortDescription: "Convert JPG and JPEG images to PNG format instantly in your browser.",
    category: "design",
    icon: "Image",
    gradient: "from-orange-500 to-rose-500",
    badge: "Image Converter",
    popular: true,
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png", "image converter"],
    howToUse: ["Upload a JPG or JPEG file.", "Preview the converted PNG.", "Download the PNG file."],
    formula: "Canvas drawImage → toDataURL('image/png')",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "png-to-jpg",
    title: "PNG to JPG Converter",
    shortDescription: "Convert PNG images to JPG/JPEG with adjustable quality.",
    category: "design",
    icon: "Image",
    gradient: "from-sky-500 to-blue-600",
    badge: "Image Converter",
    popular: true,
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg"],
    howToUse: ["Upload a PNG file.", "Adjust JPG quality if needed.", "Download the JPG file."],
    formula: "Canvas drawImage → toDataURL('image/jpeg', quality)",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "webp-to-png",
    title: "WEBP to PNG Converter",
    shortDescription: "Convert WebP images to PNG for broader compatibility.",
    category: "design",
    icon: "Image",
    gradient: "from-emerald-500 to-teal-500",
    badge: "Image Converter",
    keywords: ["webp to png", "convert webp to png"],
    howToUse: ["Upload a WebP image.", "Preview the PNG output.", "Download PNG."],
    formula: "Canvas drawImage → toDataURL('image/png')",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "png-to-webp",
    title: "PNG to WEBP Converter",
    shortDescription: "Convert PNG to WebP for smaller file sizes and faster websites.",
    category: "design",
    icon: "Image",
    gradient: "from-violet-500 to-purple-600",
    badge: "Image Converter",
    keywords: ["png to webp", "convert png to webp"],
    howToUse: ["Upload a PNG file.", "Set WebP quality.", "Download WebP."],
    formula: "Canvas drawImage → toDataURL('image/webp', quality)",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "image-compressor",
    title: "Image Compressor",
    shortDescription: "Compress JPG, PNG, and WebP images without uploading to a server.",
    category: "design",
    icon: "Minimize2",
    gradient: "from-amber-500 to-orange-500",
    badge: "Image Optimizer",
    popular: true,
    keywords: ["image compressor", "compress image online", "reduce image size"],
    howToUse: ["Upload an image.", "Adjust quality and max width.", "Compare size savings and download."],
    formula: "Resize + re-encode at lower quality → smaller byte size",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "image-resizer",
    title: "Image Resizer",
    shortDescription: "Resize images to exact width and height in pixels.",
    category: "design",
    icon: "Maximize2",
    gradient: "from-cyan-500 to-blue-500",
    badge: "Image Editor",
    keywords: ["image resizer", "resize image online", "scale image"],
    howToUse: ["Upload an image.", "Enter target width and height.", "Maintain aspect ratio or stretch.", "Download resized image."],
    formula: "Canvas scale drawImage to target dimensions",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "crop-image",
    title: "Crop Image",
    shortDescription: "Crop images to a custom region with live preview.",
    category: "design",
    icon: "Crop",
    gradient: "from-pink-500 to-rose-500",
    badge: "Image Editor",
    keywords: ["crop image online", "image cropper", "crop photo"],
    howToUse: ["Upload an image.", "Set crop X, Y, width, and height.", "Preview and download cropped image."],
    formula: "drawImage(source, sx, sy, sw, sh, 0, 0, sw, sh)",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "image-to-base64",
    title: "Image to Base64 Converter",
    shortDescription: "Encode images to Base64 data URLs for HTML, CSS, and APIs.",
    category: "design",
    icon: "FileCode",
    gradient: "from-indigo-500 to-violet-500",
    badge: "Encoder",
    keywords: ["image to base64", "base64 image encoder", "data url generator"],
    howToUse: ["Upload an image.", "Copy the Base64 string or data URL.", "Paste into HTML img src or CSS."],
    formula: "FileReader / canvas.toDataURL → Base64 string",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "base64-to-image",
    title: "Base64 to Image Decoder",
    shortDescription: "Decode Base64 strings back to downloadable image files.",
    category: "design",
    icon: "FileImage",
    gradient: "from-teal-500 to-emerald-500",
    badge: "Decoder",
    keywords: ["base64 to image", "decode base64 image", "base64 image decoder"],
    howToUse: ["Paste a Base64 or data URL string.", "Preview the decoded image.", "Download as PNG."],
    formula: "data URL → Image → canvas export",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "remove-exif",
    title: "Remove EXIF Metadata",
    shortDescription: "Strip EXIF metadata from photos by re-encoding in the browser.",
    category: "design",
    icon: "Shield",
    gradient: "from-slate-500 to-zinc-600",
    badge: "Privacy",
    keywords: ["remove exif", "strip image metadata", "remove photo metadata"],
    howToUse: ["Upload a JPG or PNG photo.", "Re-encode strips most embedded metadata.", "Download the clean image."],
    formula: "Canvas re-draw removes EXIF; metadata not copied to output",
    faq: [
      ...privacyFaq,
      { question: "Does this remove GPS location?", answer: "Re-encoding via canvas typically removes EXIF including GPS. Always verify sensitive images before sharing." },
    ],
  }),
  makeTool({
    slug: "heic-to-jpg",
    title: "HEIC to JPG Converter",
    shortDescription: "Convert iPhone HEIC photos to JPG in your browser.",
    category: "design",
    icon: "Smartphone",
    gradient: "from-blue-500 to-indigo-500",
    badge: "Image Converter",
    keywords: ["heic to jpg", "convert heic to jpeg", "iphone photo converter"],
    howToUse: ["Upload a .heic file from iPhone.", "Wait for browser conversion.", "Download JPG."],
    formula: "HEIC decode → canvas → JPEG export",
    faq: privacyFaq,
  }),
  makeTool({
    slug: "svg-to-png",
    title: "SVG to PNG Converter",
    shortDescription: "Rasterize SVG vector graphics to PNG at custom resolution.",
    category: "design",
    icon: "Layers",
    gradient: "from-fuchsia-500 to-pink-500",
    badge: "Image Converter",
    keywords: ["svg to png", "convert svg to png", "rasterize svg"],
    howToUse: ["Upload an SVG file or paste SVG markup.", "Set output width.", "Download PNG."],
    formula: "SVG → Image → canvas → PNG",
    faq: privacyFaq,
  }),
];
