import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const indiaFaq = [
  { question: "Is this India finance calculator free?", answer: "Yes. All Ranburg India tools are free with no signup." },
  { question: "Are rates and slabs current?", answer: "Calculators use common planning rates and illustrative FY slabs. Verify against official CBDT/GST notifications before filing." },
  { question: "Is this tax or legal advice?", answer: "No. Results are estimates for planning. Consult a CA or tax advisor for returns and compliance." },
  { question: "Is my salary data stored?", answer: "No. All calculations run in your browser only." },
];

export const INDIA_FINANCE_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "ctc-in-hand-calculator",
    title: "CTC to In-Hand Salary Calculator",
    shortDescription: "Estimate monthly in-hand salary from CTC with PF, gratuity, HRA exemption, and new vs old tax regime comparison.",
    category: "financial",
    icon: "Wallet",
    gradient: "from-orange-500 to-amber-600",
    badge: "India Salary",
    popular: true,
    seoTitle: "CTC to In-Hand Salary Calculator Online Free — India FY 2026-27 | Ranburg",
    keywords: ["ctc to in hand calculator", "in hand salary calculator india", "take home salary calculator", "ctc calculator india"],
    howToUse: [
      "Enter annual CTC and basic salary percentage.",
      "Set HRA, rent paid, and 80C deductions for old regime.",
      "Toggle metro city and PF cap options.",
      "Compare monthly in-hand under new vs old tax regime.",
    ],
    formula: "In-hand = (Gross − Employee PF − PT − Tax) / 12; Gross ≈ CTC − Employer PF − Gratuity",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "tds-calculator",
    title: "TDS Calculator India",
    shortDescription: "Estimate TDS on professional fees (194J), contractors (194C), rent (194I), and PAN vs no-PAN rates.",
    category: "financial",
    icon: "Receipt",
    gradient: "from-red-500 to-rose-600",
    badge: "India Tax",
    seoTitle: "TDS Calculator Online Free — Section 194J, 194C, 194I India | Ranburg",
    keywords: ["tds calculator india", "tds on professional fees", "194j tds calculator", "tds on rent 194i"],
    howToUse: [
      "Select TDS section (194J, 194C, 194I).",
      "Enter payment amount.",
      "Toggle whether payee has PAN.",
      "View TDS rate, TDS amount, and net payable.",
    ],
    formula: "TDS = Payment × rate; No-PAN often 20% or section rate, whichever is higher",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "hra-exemption-calculator",
    title: "HRA Exemption Calculator",
    shortDescription: "Calculate HRA tax exemption under Section 10(13A) — least of HRA received, rent minus 10% basic, or 40%/50% of basic.",
    category: "financial",
    icon: "Home",
    gradient: "from-emerald-500 to-green-600",
    badge: "India Tax",
    seoTitle: "HRA Exemption Calculator Online Free — Section 10(13A) India | Ranburg",
    keywords: ["hra exemption calculator", "hra calculator india", "house rent allowance exemption", "hra tax exemption"],
    howToUse: [
      "Enter annual basic salary and HRA received.",
      "Enter annual rent paid.",
      "Select metro or non-metro city.",
      "View exempt HRA and taxable HRA balance.",
    ],
    formula: "Exempt HRA = min(HRA received, 50%/40% of basic, rent paid − 10% of basic)",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "gratuity-calculator",
    title: "Gratuity Calculator India",
    shortDescription: "Estimate gratuity amount for private sector employees using (15 × last drawn salary × years) / 26 formula.",
    category: "financial",
    icon: "Award",
    gradient: "from-yellow-500 to-amber-500",
    badge: "India Salary",
    seoTitle: "Gratuity Calculator Online Free — Payment of Gratuity Act India | Ranburg",
    keywords: ["gratuity calculator india", "gratuity calculation formula", "gratuity amount calculator", "private sector gratuity"],
    howToUse: [
      "Enter last drawn monthly basic + DA.",
      "Enter completed years and extra months of service.",
      "View gratuity amount and amount above ₹20 lakh tax-free cap.",
      "Confirm eligibility (typically 5+ years) with HR.",
    ],
    formula: "Gratuity = (Last drawn salary × 15 × years of service) / 26",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "hsn-sac-finder",
    title: "HSN / SAC Code Finder",
    shortDescription: "Search common HSN and SAC GST codes with descriptions and indicative GST rates.",
    category: "financial",
    icon: "Search",
    gradient: "from-blue-500 to-indigo-600",
    badge: "India GST",
    seoTitle: "HSN SAC Code Finder Online Free — GST Tariff Search India | Ranburg",
    keywords: ["hsn code finder", "sac code finder", "gst hsn search", "hsn sac code list india"],
    howToUse: [
      "Search by HSN/SAC code or product/service description.",
      "Review code type, GST rate, and description.",
      "Verify against the official GST tariff before invoicing.",
    ],
    formula: "Sample directory keyword match on code + description fields",
    faq: [
      ...indiaFaq,
      { question: "Is this the official GST portal?", answer: "No. This is a quick reference sample. Always confirm on cbic-gst.gov.in or your ERP." },
    ],
  }),
  makeTool({
    slug: "ifsc-finder",
    title: "IFSC Code Finder",
    shortDescription: "Look up sample IFSC codes by bank name, branch, or city for NEFT, RTGS, and IMPS transfers.",
    category: "financial",
    icon: "Landmark",
    gradient: "from-cyan-500 to-teal-600",
    badge: "India Banking",
    seoTitle: "IFSC Code Finder Online Free — Bank Branch Lookup India | Ranburg",
    keywords: ["ifsc code finder", "ifsc lookup", "bank ifsc search", "find ifsc code india"],
    howToUse: [
      "Search by IFSC, bank name, branch, or city.",
      "Copy the IFSC for your transfer form.",
      "Confirm with your bank or cheque leaf before sending money.",
    ],
    formula: "Sample IFSC directory filter on IFSC, bank, branch, city",
    faq: [
      ...indiaFaq,
      { question: "Is every branch listed?", answer: "No. This uses a curated sample of major banks. Use RBI or bank websites for exhaustive lookup." },
    ],
  }),
];
