import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const indiaFaq = [
  { question: "Is this India finance calculator free?", answer: "Yes. All Ranburg India tools are free with no signup." },
  { question: "Are rates and slabs current?", answer: "Calculators use common planning rates and illustrative FY slabs. Verify against official CBDT/GST notifications before filing." },
  { question: "Is this tax or legal advice?", answer: "No. Results are estimates for planning. Consult a CA or tax advisor for returns and compliance." },
  { question: "Is my salary data stored?", answer: "No. All calculations run in your browser only." },
];

export const INDIA_FINANCE_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "ctc-in-hand-calculator",
    title: "CTC to In-Hand Salary Calculator",
    shortDescription: "Estimate monthly in-hand salary from CTC with PF, gratuity, HRA exemption, and new vs old tax regime comparison.",
    category: "financial",
    icon: "Wallet",
    gradient: "from-orange-500 to-amber-600",
    badge: "India Salary",
    popular: true,
    seoTitle: "CTC to In-Hand Salary Calculator Online Free — India FY 2026-27 | Ranburg",
    keywords: ["ctc to in hand calculator", "in hand salary calculator india", "take home salary calculator", "ctc calculator india"],
    howToUse: [
      "Enter annual CTC and basic salary percentage.",
      "Set HRA, rent paid, and 80C deductions for old regime.",
      "Toggle metro city and PF cap options.",
      "Compare monthly in-hand under new vs old tax regime.",
    ],
    formula: "In-hand = (Gross − Employee PF − PT − Tax) / 12; Gross ≈ CTC − Employer PF − Gratuity",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "tds-calculator",
    title: "TDS Calculator India",
    shortDescription: "Estimate TDS on professional fees (194J), contractors (194C), rent (194I), and PAN vs no-PAN rates.",
    category: "financial",
    icon: "Receipt",
    gradient: "from-red-500 to-rose-600",
    badge: "India Tax",
    seoTitle: "TDS Calculator Online Free — Section 194J, 194C, 194I India | Ranburg",
    keywords: ["tds calculator india", "tds on professional fees", "194j tds calculator", "tds on rent 194i"],
    howToUse: [
      "Select TDS section (194J, 194C, 194I).",
      "Enter payment amount.",
      "Toggle whether payee has PAN.",
      "View TDS rate, TDS amount, and net payable.",
    ],
    formula: "TDS = Payment × rate; No-PAN often 20% or section rate, whichever is higher",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "hra-exemption-calculator",
    title: "HRA Exemption Calculator",
    shortDescription: "Calculate HRA tax exemption under Section 10(13A) — least of HRA received, rent minus 10% basic, or 40%/50% of basic.",
    category: "financial",
    icon: "Home",
    gradient: "from-emerald-500 to-green-600",
    badge: "India Tax",
    seoTitle: "HRA Exemption Calculator Online Free — Section 10(13A) India | Ranburg",
    keywords: ["hra exemption calculator", "hra calculator india", "house rent allowance exemption", "hra tax exemption"],
    howToUse: [
      "Enter annual basic salary and HRA received.",
      "Enter annual rent paid.",
      "Select metro or non-metro city.",
      "View exempt HRA and taxable HRA balance.",
    ],
    formula: "Exempt HRA = min(HRA received, 50%/40% of basic, rent paid − 10% of basic)",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "gratuity-calculator",
    title: "Gratuity Calculator India",
    shortDescription: "Estimate gratuity amount for private sector employees using (15 × last drawn salary × years) / 26 formula.",
    category: "financial",
    icon: "Award",
    gradient: "from-yellow-500 to-amber-500",
    badge: "India Salary",
    seoTitle: "Gratuity Calculator Online Free — Payment of Gratuity Act India | Ranburg",
    keywords: ["gratuity calculator india", "gratuity calculation formula", "gratuity amount calculator", "private sector gratuity"],
    howToUse: [
      "Enter last drawn monthly basic + DA.",
      "Enter completed years and extra months of service.",
      "View gratuity amount and amount above ₹20 lakh tax-free cap.",
      "Confirm eligibility (typically 5+ years) with HR.",
    ],
    formula: "Gratuity = (Last drawn salary × 15 × years of service) / 26",
    faq: indiaFaq,
  }),
  makeTool({
    slug: "hsn-sac-finder",
    title: "HSN / SAC Code Finder",
    shortDescription: "Search common HSN and SAC GST codes with descriptions and indicative GST rates.",
    category: "financial",
    icon: "Search",
    gradient: "from-blue-500 to-indigo-600",
    badge: "India GST",
    seoTitle: "HSN SAC Code Finder Online Free — GST Tariff Search India | Ranburg",
    keywords: ["hsn code finder", "sac code finder", "gst hsn search", "hsn sac code list india"],
    howToUse: [
      "Search by HSN/SAC code or product/service description.",
      "Review code type, GST rate, and description.",
      "Verify against the official GST tariff before invoicing.",
    ],
    formula: "Sample directory keyword match on code + description fields",
    faq: [
      ...indiaFaq,
      { question: "Is this the official GST portal?", answer: "No. This is a quick reference sample. Always confirm on cbic-gst.gov.in or your ERP." },
    ],
  }),
  makeTool({
    slug: "ifsc-finder",
    title: "IFSC Code Finder",
    shortDescription: "Look up sample IFSC codes by bank name, branch, or city for NEFT, RTGS, and IMPS transfers.",
    category: "financial",
    icon: "Landmark",
    gradient: "from-cyan-500 to-teal-600",
    badge: "India Banking",
    seoTitle: "IFSC Code Finder Online Free — Bank Branch Lookup India | Ranburg",
    keywords: ["ifsc code finder", "ifsc lookup", "bank ifsc search", "find ifsc code india"],
    howToUse: [
      "Search by IFSC, bank name, branch, or city.",
      "Copy the IFSC for your transfer form.",
      "Confirm with your bank or cheque leaf before sending money.",
    ],
    formula: "Sample IFSC directory filter on IFSC, bank, branch, city",
    faq: [
      ...indiaFaq,
      { question: "Is every branch listed?", answer: "No. This uses a curated sample of major banks. Use RBI or bank websites for exhaustive lookup." },
    ],
  }),
  makeTool({
    slug: "lic-maturity-calculator",
    title: "LIC Maturity Calculator",
    shortDescription:
      "Pick an LIC plan (Jeevan Labh, New Jeevan Anand, New Endowment, money-back & more) — term/PPT and illustrative bonus bands drive the maturity estimate.",
    category: "financial",
    icon: "ShieldCheck",
    gradient: "from-indigo-500 to-blue-600",
    badge: "LIC Planner",
    popular: true,
    seoTitle: "LIC Maturity Calculator Online Free — Jeevan Labh, Anand & Plan-wise Estimator | Ranburg",
    seoDescription:
      "Free LIC maturity calculator by plan. Select Jeevan Labh, New Jeevan Anand, New Endowment or money-back — auto term/PPT and bonus bands estimate maturity amount online.",
    keywords: [
      "lic maturity calculator",
      "lic maturity amount calculator",
      "lic jeevan labh maturity calculator",
      "lic jeevan anand maturity calculator",
      "lic new endowment maturity calculator",
      "lic money back maturity calculator",
      "lic plan wise maturity calculator",
      "lic bonus calculator",
      "lic policy maturity calculator",
      "lic maturity value calculator",
      "lic jeevan lakshya calculator",
      "lic jeevan tarun maturity",
      "how to calculate lic maturity amount",
      "lic maturity calculator india",
      "estimate lic maturity amount online free",
    ],
    howToUse: [
      "Select your LIC plan from the list (Jeevan Labh, New Jeevan Anand, New Endowment, money-back, etc.).",
      "Choose the allowed policy term / PPT combination for that plan.",
      "Enter sum assured, premium, years elapsed, and start year.",
      "Review auto-filled reversionary bonus and FAB (override if your statement differs).",
      "Copy the estimated maturity into the SWP calculator as a future top-up.",
    ],
    formula:
      "Maturity ≈ (SA × plan maturity factor) + (Bonus ₹/1000 × SA/1000 × term) + (FAB ₹/1000 × SA/1000); bonus rate from plan + term + SA band",
    faq: [
      ...indiaFaq,
      {
        question: "Does this fetch live LIC policy data by policy number?",
        answer:
          "No. LIC does not offer a public API for that. Choose your plan, enter SA and premiums, and we estimate using plan rules and illustrative bonus bands.",
      },
      {
        question: "Which LIC plans are supported?",
        answer:
          "Jeevan Labh, New Jeevan Anand, New Endowment, Jeevan Lakshya, Single Premium Endowment, Jeevan Tarun, New Children’s Money Back, Money Back 20/25, plus a Custom option.",
      },
      {
        question: "Are bonus rates guaranteed?",
        answer:
          "No. Auto rates are illustrative published-style bands by plan/term/SA. Override from your bonus statement. FAB is especially variable.",
      },
    ],
  }),
  makeTool({
    slug: "pf-calculator",
    title: "PF Calculator",
    shortDescription:
      "Project EPF / PF corpus with existing balance, monthly contributions, annual salary hike, and PF interest rate.",
    category: "financial",
    icon: "PiggyBank",
    gradient: "from-teal-500 to-emerald-600",
    badge: "EPF Planner",
    popular: true,
    seoTitle: "PF Calculator Online Free — EPF Balance & Salary Hike Projection India | Ranburg",
    seoDescription:
      "Free PF calculator / EPF calculator India. Project provident fund corpus with existing PF balance, monthly contribution, average salary hike per annum, and EPFO interest — online free.",
    keywords: [
      "pf calculator",
      "epf calculator",
      "pf calculator india",
      "epf balance calculator",
      "provident fund calculator",
      "pf interest calculator",
      "epf corpus calculator",
      "pf contribution calculator",
      "employee provident fund calculator",
      "pf calculator with salary hike",
      "epf projection calculator",
      "how much will my pf be",
      "pf maturity calculator",
      "uan pf calculator",
      "epf calculator with existing balance",
    ],
    howToUse: [
      "Enter existing PF balance and current monthly basic.",
      "Set employee and employer contribution percentages.",
      "Choose average salary hike per year and PF interest rate.",
      "Select years to project and optional ₹1,800 monthly cap.",
      "View projected corpus, contributions, and interest earned.",
    ],
    formula:
      "Each month: Balance = Balance × (1 + r/12) + Employee%×Basic + Employer%×Basic; Basic grows by salary hike each year",
    faq: [
      ...indiaFaq,
      {
        question: "Does this connect to EPFO / UAN?",
        answer: "No. It is a browser-only projection. Check your real passbook on the EPFO member portal.",
      },
      {
        question: "Should I include EPS?",
        answer:
          "This model treats employer % as going into the interest-bearing PF pot for simplicity. In reality a portion may go to EPS — adjust employer % if you want a conservative estimate.",
      },
    ],
  }),
];
