import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const browserFaq = [
  { question: "Is this tool free?", answer: "Yes. All Ranburg tools are free with no signup." },
  { question: "Are my files uploaded to a server?", answer: "No. Processing runs entirely in your browser." },
  { question: "Can I use this commercially?", answer: "Yes. Outputs are yours to use for personal or commercial projects." },
  { question: "Does it work on mobile?", answer: "Most tools work on modern mobile browsers; large files may be slower on phones." },
];

const creatorFaq = [
  ...browserFaq,
  { question: "Are safe zones exact?", answer: "Overlays are approximate guides based on common platform UI — always preview on each app." },
];

export const NEW_WAVE_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "safe-zone-checker",
    title: "Safe Zone Checker",
    shortDescription: "Preview TikTok, Reels, and Shorts UI safe zones on your vertical video thumbnail or frame.",
    category: "design",
    icon: "Smartphone",
    gradient: "from-violet-500 to-purple-600",
    badge: "Creator QA",
    popular: true,
    seoTitle: "Safe Zone Checker Online Free — TikTok, Reels & Shorts Overlay | Ranburg",
    keywords: ["safe zone checker", "tiktok safe zone", "reels safe zone", "youtube shorts safe area", "vertical video overlay"],
    howToUse: [
      "Upload a vertical image or video frame screenshot.",
      "Switch between TikTok, Reels, and Shorts presets.",
      "Keep key text and faces inside the green safe box.",
      "Download the annotated preview to share with your editor.",
    ],
    formula: "Danger zones ≈ top 10–12%, bottom 20–24%, right 12–14% for vertical 9:16 UI chrome",
    faq: creatorFaq,
  }),
  makeTool({
    slug: "youtube-thumbnail-checker",
    title: "YouTube Thumbnail Checker",
    shortDescription: "Validate YouTube thumbnail size, 16:9 ratio, 1280×720 recommendation, and 2 MB limit with safe zone overlay.",
    category: "design",
    icon: "Youtube",
    gradient: "from-red-600 to-red-500",
    badge: "Creator QA",
    popular: true,
    seoTitle: "YouTube Thumbnail Checker Online Free — Size & Safe Zone | Ranburg",
    keywords: ["youtube thumbnail checker", "youtube thumbnail size", "1280x720 thumbnail", "thumbnail safe zone"],
    howToUse: [
      "Upload your thumbnail JPG or PNG.",
      "Review pass, warn, and fail checks for ratio, resolution, and file size.",
      "Adjust title text to stay inside the green safe area.",
      "Export a corrected 1280×720 image if checks fail.",
    ],
    formula: "16:9 ratio · min width 640px · recommended 1280×720 · max file size 2 MB",
    faq: [
      ...browserFaq,
      { question: "What is the best YouTube thumbnail size?", answer: "1280×720 pixels at 16:9 aspect ratio, under 2 MB." },
    ],
  }),
  makeTool({
    slug: "social-image-size-checker",
    title: "Social Image Size Checker",
    shortDescription: "See which social platforms your image fits — Instagram, LinkedIn, X, Pinterest, YouTube, and vertical video specs.",
    category: "design",
    icon: "Image",
    gradient: "from-pink-500 to-rose-500",
    badge: "Creator QA",
    seoTitle: "Social Image Size Checker Online Free — IG, LinkedIn, X & More | Ranburg",
    keywords: ["social media image size", "instagram image dimensions", "linkedin post size", "pinterest pin size", "social image checker"],
    howToUse: [
      "Upload any image.",
      "Compare your dimensions against platform target sizes.",
      "Use pass/warn/fail to decide if you need crop or resize.",
      "Resize with Ranburg image tools if needed.",
    ],
    formula: "Fit score from aspect ratio delta + resolution vs platform target (1080×1350, 1080×1920, 1280×720, etc.)",
    faq: browserFaq,
  }),
  makeTool({
    slug: "compress-to-exact-size",
    title: "Compress to Exact Size",
    shortDescription: "Binary-search JPEG quality to hit an exact target file size in KB — useful for upload limits.",
    category: "design",
    icon: "Minimize2",
    gradient: "from-cyan-500 to-blue-600",
    badge: "Image Tool",
    seoTitle: "Compress Image to Exact Size Online Free — Target KB | Ranburg",
    keywords: ["compress to exact size", "image target file size", "jpeg quality calculator", "compress image kb"],
    howToUse: [
      "Upload a JPG or PNG.",
      "Set your target size in KB with the slider.",
      "Run compression — quality is tuned via binary search.",
      "Download the JPEG at or near your target size.",
    ],
    formula: "Binary search JPEG quality q until file size ≤ target KB",
    faq: browserFaq,
  }),
  makeTool({
    slug: "youtube-chapter-generator",
    title: "YouTube Chapter Generator",
    shortDescription: "Turn timestamp lines into a copy-ready YouTube chapters block for your video description.",
    category: "productivity",
    icon: "List",
    gradient: "from-red-500 to-orange-500",
    badge: "YouTube SEO",
    popular: true,
    seoTitle: "YouTube Chapter Generator Online Free — Timestamp Chapters | Ranburg",
    keywords: ["youtube chapter generator", "youtube timestamps", "video chapters", "youtube description chapters"],
    howToUse: [
      "Enter one chapter per line: 0:00 Intro, 1:30 Topic, etc.",
      "Ensure the first chapter starts at 0:00.",
      "Copy the generated block into your video description.",
      "YouTube requires 3+ chapters spaced at least 10 seconds apart.",
    ],
    formula: "Lines formatted as M:SS Title → YouTube description chapter block",
    faq: browserFaq,
  }),

  makeTool({
    slug: "avif-to-jpg",
    title: "AVIF to JPG Converter",
    shortDescription: "Convert AVIF images to JPEG in your browser using canvas decode — no upload required.",
    category: "design",
    icon: "ImageDown",
    gradient: "from-teal-500 to-emerald-600",
    badge: "Format Converter",
    seoTitle: "AVIF to JPG Converter Online Free — Browser Decode | Ranburg",
    keywords: ["avif to jpg", "avif converter", "convert avif to jpeg", "avif to jpg online"],
    howToUse: ["Upload an .avif file.", "Adjust JPEG quality.", "Download the converted JPG instantly."],
    formula: "createImageBitmap(AVIF) → canvas → JPEG export",
    faq: browserFaq,
  }),
  makeTool({
    slug: "jpg-to-avif",
    title: "JPG to AVIF Converter",
    shortDescription: "Convert JPEG to AVIF when your browser supports AVIF encoding; PNG fallback otherwise.",
    category: "design",
    icon: "ImageUp",
    gradient: "from-emerald-500 to-teal-600",
    badge: "Format Converter",
    seoTitle: "JPG to AVIF Converter Online Free — Browser Encode | Ranburg",
    keywords: ["jpg to avif", "jpeg to avif", "convert jpg to avif", "avif encoder online"],
    howToUse: [
      "Upload a JPG or JPEG.",
      "If your browser supports AVIF encoding, download .avif.",
      "Otherwise a PNG fallback is offered with a clear notice.",
    ],
    formula: "canvas.toBlob('image/avif') when supported, else PNG fallback",
    faq: browserFaq,
  }),
  makeTool({
    slug: "opus-to-mp3",
    title: "Opus to MP3 Converter",
    shortDescription: "Convert Opus/Ogg audio to MP3 locally with FFmpeg WASM — client-only, no server upload.",
    category: "productivity",
    icon: "Music",
    gradient: "from-indigo-500 to-violet-600",
    badge: "Audio Converter",
    seoTitle: "Opus to MP3 Converter Online Free — Client-Side FFmpeg | Ranburg",
    keywords: ["opus to mp3", "ogg to mp3", "convert opus online", "opus mp3 converter free"],
    howToUse: [
      "Install @ffmpeg/ffmpeg and @ffmpeg/util if prompted.",
      "Upload an Opus or Ogg audio file.",
      "Wait for WASM conversion in your browser.",
      "Download the MP3 output.",
    ],
    formula: "FFmpeg: ffmpeg -i input.opus -codec:a libmp3lame -q:a 2 output.mp3",
    faq: [
      ...browserFaq,
      { question: "Why do I need to install FFmpeg packages?", answer: "The site loads FFmpeg WASM dynamically. Run npm install @ffmpeg/ffmpeg @ffmpeg/util in the project for full support." },
    ],
  }),
  makeTool({
    slug: "csv-to-json",
    title: "CSV to JSON Converter",
    shortDescription: "Convert CSV with header row to formatted JSON arrays in your browser.",
    category: "developer",
    icon: "Braces",
    gradient: "from-slate-600 to-zinc-700",
    badge: "Data Converter",
    seoTitle: "CSV to JSON Converter Online Free — Instant Parse | Ranburg",
    keywords: ["csv to json", "convert csv to json", "csv json converter online"],
    howToUse: ["Paste CSV with a header row.", "Review JSON output.", "Copy or use in your app."],
    formula: "Header row → keys; each data row → JSON object in array",
    faq: browserFaq,
  }),
  makeTool({
    slug: "json-to-csv",
    title: "JSON to CSV Converter",
    shortDescription: "Flatten a JSON array of objects into CSV with automatic headers.",
    category: "developer",
    icon: "Table",
    gradient: "from-zinc-600 to-slate-700",
    badge: "Data Converter",
    seoTitle: "JSON to CSV Converter Online Free — Array to Spreadsheet | Ranburg",
    keywords: ["json to csv", "convert json to csv", "json csv converter online"],
    howToUse: ["Paste a JSON array of objects.", "Copy the generated CSV.", "Open in Excel or Google Sheets."],
    formula: "Union of object keys → header; values escaped for CSV",
    faq: browserFaq,
  }),
  makeTool({
    slug: "excel-to-csv",
    title: "Excel to CSV Converter",
    shortDescription: "Convert .xlsx and .xls workbooks to CSV per sheet in your browser.",
    category: "productivity",
    icon: "Sheet",
    gradient: "from-green-600 to-emerald-700",
    badge: "Spreadsheet Tool",
    seoTitle: "Excel to CSV Converter Online Free — XLSX to CSV | Ranburg",
    keywords: ["excel to csv", "xlsx to csv", "convert excel to csv online", "spreadsheet to csv"],
    howToUse: [
      "Upload an Excel file (.xlsx, .xls).",
      "Select a sheet if the workbook has multiple tabs.",
      "Copy or save the CSV output.",
    ],
    formula: "SheetJS read → sheet_to_csv per worksheet",
    faq: [
      ...browserFaq,
      { question: "Which Excel formats are supported?", answer: ".xlsx, .xls, and .xlsm via the xlsx library." },
    ],
  }),
  makeTool({
    slug: "face-blur",
    title: "Face Blur Tool",
    shortDescription: "Draw rectangles on an image to pixelate faces or sensitive regions, then download PNG.",
    category: "design",
    icon: "ScanFace",
    gradient: "from-blue-500 to-indigo-600",
    badge: "Privacy Tool",
    seoTitle: "Face Blur Tool Online Free — Pixelate Regions in Browser | Ranburg",
    keywords: ["face blur tool", "blur faces online", "pixelate image", "privacy blur photo"],
    howToUse: [
      "Upload a photo.",
      "Click and drag rectangles over faces or sensitive areas.",
      "Adjust pixel block size.",
      "Download the blurred PNG.",
    ],
    formula: "Region pixelate via downscale-upscale on canvas patches",
    faq: browserFaq,
  }),

  makeTool({
    slug: "burn-rate-runway-calculator",
    title: "Burn Rate & Runway Calculator",
    shortDescription: "Calculate gross/net burn, runway months, cash-out date, and default-alive with optional revenue growth.",
    category: "financial",
    icon: "Flame",
    gradient: "from-orange-500 to-red-600",
    badge: "Startup Calculator",
    popular: true,
    seoTitle: "Burn Rate Runway Calculator Online Free — Startup Cash Planning | Ranburg",
    keywords: ["burn rate calculator", "startup runway", "cash runway calculator", "net burn rate", "default alive"],
    howToUse: [
      "Enter cash on hand, monthly expenses, and revenue.",
      "View gross burn, net burn, and runway in months.",
      "Enable revenue growth to model default-alive scenarios.",
      "Use cash-out date for fundraising timelines.",
    ],
    formula: "Net burn = expenses − revenue; Runway = cash ÷ net burn (or growth simulation)",
    faq: [
      { question: "Is this calculator free?", answer: "Yes. No signup required." },
      { question: "What is net burn?", answer: "Monthly expenses minus monthly revenue. Negative net burn means cash-flow positive." },
      { question: "What is default alive?", answer: "A startup reaches default alive when revenue growth covers burn before cash runs out." },
      { question: "Is this financial advice?", answer: "No. Use for planning estimates only." },
    ],
  }),
  makeTool({
    slug: "freelancer-hourly-rate-calculator",
    title: "Freelancer Hourly Rate Calculator",
    shortDescription: "Back into an hourly rate from desired salary, taxes, benefits, and billable hours.",
    category: "financial",
    icon: "Clock",
    gradient: "from-sky-500 to-blue-600",
    badge: "Freelance Calculator",
    seoTitle: "Freelancer Hourly Rate Calculator Online Free — Price Your Time | Ranburg",
    keywords: ["freelancer hourly rate calculator", "consulting rate calculator", "freelance pricing", "billable rate calculator"],
    howToUse: [
      "Set your target annual salary.",
      "Add effective tax rate and benefits/overhead.",
      "Enter billable hours per week and weeks per year.",
      "Use the hourly and day rate in proposals.",
    ],
    formula: "Hourly = (salary ÷ (1 − tax%) + overhead) ÷ (hours/week × weeks/year)",
    faq: [
      { question: "Should I include taxes?", answer: "Yes. Self-employed workers should gross up for income and self-employment taxes." },
      { question: "How many billable hours is realistic?", answer: "Many freelancers bill 25–30 hours per week after sales and admin." },
      { question: "Is this free?", answer: "Yes." },
      { question: "Can I use this for agency pricing?", answer: "Yes. Adjust overhead for team and tool costs." },
    ],
  }),
  makeTool({
    slug: "ab-test-significance-calculator",
    title: "A/B Test Significance Calculator",
    shortDescription: "Two-proportion z-test for A/B conversions plus sample size planner for MDE at 80% power.",
    category: "financial",
    icon: "GitCompare",
    gradient: "from-purple-500 to-fuchsia-600",
    badge: "Analytics Calculator",
    seoTitle: "A/B Test Significance Calculator Online Free — Z-Test & Sample Size | Ranburg",
    keywords: ["ab test significance calculator", "ab test sample size", "conversion rate significance", "z test ab test"],
    howToUse: [
      "Enter visitors and conversions for variants A and B.",
      "Read p-value and significance at 95% confidence.",
      "Use the sample size planner before launching tests.",
      "Set baseline conversion and minimum detectable effect.",
    ],
    formula: "Two-proportion z-test; n ≈ 2p(1−p)(zα/2 + zβ)² / δ²",
    faq: [
      { question: "What p-value means significant?", answer: "p < 0.05 is commonly used for 95% confidence." },
      { question: "Is this a full Bayesian calculator?", answer: "No. This uses a frequentist two-proportion z-test approximation." },
      { question: "What is MDE?", answer: "Minimum detectable effect — the smallest relative lift you want to detect." },
      { question: "Is my data sent anywhere?", answer: "No. All math runs locally." },
    ],
  }),
  makeTool({
    slug: "ai-crawler-robots-checker",
    title: "AI Crawler Robots.txt Checker",
    shortDescription: "Paste robots.txt and see allow/disallow status for GPTBot, ClaudeBot, Google-Extended, and other AI crawlers.",
    category: "developer",
    icon: "Bot",
    gradient: "from-neutral-600 to-stone-700",
    badge: "SEO & AI",
    seoTitle: "AI Crawler Robots.txt Checker Online Free — GPTBot & ClaudeBot | Ranburg",
    keywords: ["ai crawler robots.txt", "gptbot robots", "claudebot disallow", "ai bot blocker checker"],
    howToUse: [
      "Paste your robots.txt content.",
      "Review allow/disallow for each AI user-agent.",
      "Update your live robots.txt on your server accordingly.",
      "Combine with llms.txt for LLM-specific guidance.",
    ],
    formula: "Parse User-agent blocks → match bot name or fall back to * rules",
    faq: browserFaq,
  }),
  makeTool({
    slug: "llms-txt-generator",
    title: "llms.txt Generator",
    shortDescription: "Generate an llms.txt markdown file from your site name and curated URL list for LLM crawlers.",
    category: "developer",
    icon: "FileText",
    gradient: "from-stone-600 to-neutral-700",
    badge: "SEO & AI",
    seoTitle: "llms.txt Generator Online Free — LLM Crawler Markdown | Ranburg",
    keywords: ["llms.txt generator", "llms txt", "llm crawler file", "ai site map markdown"],
    howToUse: [
      "Enter your site or project name.",
      "Add URLs one per line with optional titles (url | title).",
      "Copy the generated llms.txt.",
      "Host at https://yoursite.com/llms.txt",
    ],
    formula: "Markdown header + bullet list of [title](url) entries",
    faq: browserFaq,
  }),
  makeTool({
    slug: "jwt-decoder",
    title: "JWT Decoder",
    shortDescription: "Decode JWT header and payload in your browser — view exp date and optionally verify HS256 signatures.",
    category: "developer",
    icon: "KeyRound",
    gradient: "from-amber-500 to-orange-600",
    badge: "Security Tool",
    popular: true,
    seoTitle: "JWT Decoder Online Free — Decode Token Header & Payload | Ranburg",
    keywords: ["jwt decoder", "decode jwt online", "jwt parser", "json web token decoder"],
    howToUse: [
      "Paste a JWT (three base64url segments).",
      "Inspect header and payload JSON.",
      "Check exp claim as a human-readable date.",
      "Optionally verify HS256 with your secret — never on untrusted machines.",
    ],
    formula: "base64url decode header.payload; exp → Date; HMAC-SHA256 optional verify",
    faq: [
      ...browserFaq,
      { question: "Is my token sent to a server?", answer: "Never. Decoding is 100% client-side." },
      { question: "Can this verify RS256 tokens?", answer: "Only HS256 with a shared secret is supported here. RS256 needs a public key workflow." },
    ],
  }),
];
