import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const pdfFaq = [
  { question: "Are PDFs uploaded to Ranburg servers?", answer: "No. PDF processing runs entirely in your browser using WebAssembly and JavaScript." },
  { question: "Is there a file size limit?", answer: "Browser memory limits apply. Most documents under 50MB work well." },
  { question: "Is this tool free?", answer: "Yes. All PDF tools on Ranburg.com are free." },
];

export const PDF_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "pdf-merge",
    title: "PDF Merge",
    shortDescription: "Combine multiple PDF files into one document — drag, drop, merge.",
    category: "productivity",
    icon: "Files",
    gradient: "from-red-500 to-rose-600",
    badge: "PDF Tool",
    popular: true,
    keywords: ["merge pdf", "combine pdf", "join pdf files"],
    howToUse: ["Upload two or more PDF files.", "Drag to reorder if needed.", "Click Merge and download."],
    formula: "pdf-lib copyPages → single PDFDocument",
    faq: pdfFaq,
  }),
  makeTool({
    slug: "pdf-split",
    title: "PDF Split",
    shortDescription: "Split a PDF into separate files — one PDF per page.",
    category: "productivity",
    icon: "SplitSquareHorizontal",
    gradient: "from-orange-500 to-amber-500",
    badge: "PDF Tool",
    popular: true,
    keywords: ["split pdf", "pdf splitter", "separate pdf pages"],
    howToUse: ["Upload a PDF.", "Click Split.", "Download a ZIP of individual page PDFs."],
    formula: "One page per PDFDocument → zip download",
    faq: pdfFaq,
  }),
  makeTool({
    slug: "pdf-compressor",
    title: "PDF Compressor",
    shortDescription: "Reduce PDF file size by optimizing and re-saving in the browser.",
    category: "productivity",
    icon: "Minimize2",
    gradient: "from-yellow-500 to-orange-500",
    badge: "PDF Optimizer",
    keywords: ["compress pdf", "reduce pdf size", "pdf optimizer"],
    howToUse: ["Upload a PDF.", "Choose compression level.", "Download optimized PDF."],
    formula: "pdf-lib reload + save with object streams",
    faq: pdfFaq,
  }),
  makeTool({
    slug: "pdf-to-jpg",
    title: "PDF to JPG Converter",
    shortDescription: "Convert PDF pages to JPG images for sharing and editing.",
    category: "productivity",
    icon: "Image",
    gradient: "from-pink-500 to-red-500",
    badge: "PDF Converter",
    keywords: ["pdf to jpg", "pdf to jpeg", "convert pdf to image"],
    howToUse: ["Upload a PDF.", "Select page or all pages.", "Download JPG images."],
    formula: "PDF.js render page → canvas → JPEG",
    faq: pdfFaq,
  }),
  makeTool({
    slug: "jpg-to-pdf",
    title: "JPG to PDF Converter",
    shortDescription: "Convert JPG and PNG images into a single PDF document.",
    category: "productivity",
    icon: "FileText",
    gradient: "from-blue-500 to-cyan-500",
    badge: "PDF Converter",
    popular: true,
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf"],
    howToUse: ["Upload one or more images.", "Reorder if needed.", "Download combined PDF."],
    formula: "pdf-lib embedPng/Jpeg → addPage per image",
    faq: pdfFaq,
  }),
  makeTool({
    slug: "word-to-pdf",
    title: "Text to PDF Converter",
    shortDescription: "Paste text or upload a .txt file and download a clean PDF — browser-based, no Word install.",
    category: "productivity",
    icon: "FileType",
    gradient: "from-indigo-500 to-blue-600",
    badge: "PDF Converter",
    keywords: ["text to pdf", "word to pdf", "document to pdf", "paste to pdf"],
    howToUse: ["Paste text or upload a plain .txt file.", "Set a document title.", "Download your PDF."],
    formula: "pdf-lib drawText with line wrapping",
    faq: [
      ...pdfFaq,
      {
        question: "Does this convert .docx Word files?",
        answer:
          "Not directly. Paste text from Word or upload a .txt file. Full .docx parsing needs desktop software — this tool creates PDFs from text content honestly and instantly.",
      },
    ],
  }),
  makeTool({
    slug: "pdf-page-extractor",
    title: "PDF Page Extractor",
    shortDescription: "Extract specific pages from a PDF by page range.",
    category: "productivity",
    icon: "FileOutput",
    gradient: "from-emerald-500 to-green-600",
    badge: "PDF Tool",
    keywords: ["extract pdf pages", "pdf page extractor", "get pages from pdf"],
    howToUse: ["Upload a PDF.", "Enter page range (e.g. 1-3, 5).", "Download extracted PDF."],
    formula: "pdf-lib copyPages(indices) → new PDF",
    faq: pdfFaq,
  }),
  makeTool({
    slug: "pdf-page-remover",
    title: "PDF Page Remover",
    shortDescription: "Delete unwanted pages from a PDF document.",
    category: "productivity",
    icon: "FileX",
    gradient: "from-rose-500 to-red-600",
    badge: "PDF Tool",
    keywords: ["remove pdf pages", "delete pages from pdf", "pdf page remover"],
    howToUse: ["Upload a PDF.", "Enter pages to remove.", "Download PDF without those pages."],
    formula: "pdf-lib copy all except removed indices",
    faq: pdfFaq,
  }),
];
