import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const seoFaq = [
  { question: "Is my content sent to a server?", answer: "No. SEO tools process your text locally in the browser." },
  { question: "Can I use output on client websites?", answer: "Yes. Generated meta tags, robots.txt, and schema are yours to use commercially." },
  { question: "Is this tool free?", answer: "Yes. All Ranburg SEO tools are free." },
];

export const SEO_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "keyword-density-checker",
    title: "Keyword Density Checker",
    shortDescription: "Analyze keyword frequency and density in your content for on-page SEO.",
    category: "productivity",
    icon: "Search",
    gradient: "from-emerald-500 to-teal-500",
    badge: "SEO Analyzer",
    popular: true,
    keywords: ["keyword density checker", "keyword frequency", "seo keyword tool"],
    howToUse: ["Paste your article or page copy.", "View word count and keyword percentages.", "Optimize over-stuffed terms."],
    formula: "keyword count / total words × 100",
    faq: seoFaq,
  }),
  makeTool({
    slug: "meta-tag-generator",
    title: "Meta Tag Generator",
    shortDescription: "Generate title, description, and canonical meta tags for any page.",
    category: "productivity",
    icon: "Tags",
    gradient: "from-blue-500 to-indigo-500",
    badge: "SEO Generator",
    popular: true,
    keywords: ["meta tag generator", "title meta description", "html meta tags"],
    howToUse: ["Enter page title and description.", "Add URL and robots directives.", "Copy HTML meta tags."],
    formula: "<title>, <meta name='description'>, <link rel='canonical'>",
    faq: seoFaq,
  }),
  makeTool({
    slug: "robots-txt-generator",
    title: "Robots.txt Generator",
    shortDescription: "Build robots.txt files with allow/disallow rules and sitemap URL.",
    category: "productivity",
    icon: "Bot",
    gradient: "from-slate-500 to-gray-600",
    badge: "SEO Generator",
    keywords: ["robots txt generator", "robots.txt builder", "crawl rules"],
    howToUse: ["Set user-agent rules.", "Add disallow/allow paths.", "Include sitemap URL.", "Copy robots.txt."],
    formula: "User-agent + Disallow/Allow + Sitemap directives",
    faq: seoFaq,
  }),
  makeTool({
    slug: "xml-sitemap-generator",
    title: "XML Sitemap Generator",
    shortDescription: "Create XML sitemaps from a list of URLs with priority and changefreq.",
    category: "productivity",
    icon: "Map",
    gradient: "from-violet-500 to-purple-600",
    badge: "SEO Generator",
    keywords: ["xml sitemap generator", "sitemap builder", "sitemap xml"],
    howToUse: ["Enter URLs one per line.", "Set default priority and changefreq.", "Copy or download sitemap.xml."],
    formula: "urlset → url → loc, lastmod, changefreq, priority",
    faq: seoFaq,
  }),
  makeTool({
    slug: "open-graph-generator",
    title: "Open Graph Generator",
    shortDescription: "Generate Open Graph and Twitter Card meta tags for social sharing.",
    category: "productivity",
    icon: "Share2",
    gradient: "from-sky-500 to-blue-500",
    badge: "Social SEO",
    keywords: ["open graph generator", "og meta tags", "twitter card generator"],
    howToUse: ["Enter title, description, image URL, and page URL.", "Copy OG and Twitter meta tags.", "Paste into page <head>."],
    formula: "og:title, og:description, og:image, twitter:card",
    faq: seoFaq,
  }),
  makeTool({
    slug: "schema-markup-generator",
    title: "Schema Markup Generator",
    shortDescription: "Build JSON-LD structured data for articles, products, FAQs, and organizations.",
    category: "productivity",
    icon: "Braces",
    gradient: "from-amber-500 to-orange-500",
    badge: "Structured Data",
    keywords: ["schema markup generator", "json-ld generator", "structured data tool"],
    howToUse: ["Choose schema type.", "Fill required fields.", "Copy JSON-LD script tag."],
    formula: "JSON-LD @context schema.org → @type + properties",
    faq: seoFaq,
  }),
  makeTool({
    slug: "url-encoder-decoder",
    title: "URL Encoder / Decoder",
    shortDescription: "Encode and decode URLs and query strings for safe transmission.",
    category: "developer",
    icon: "Link",
    gradient: "from-cyan-500 to-teal-500",
    badge: "Encoder",
    keywords: ["url encoder", "url decoder", "percent encoding"],
    howToUse: ["Paste text or URL.", "Switch encode/decode mode.", "Copy result."],
    formula: "encodeURIComponent / decodeURIComponent",
    faq: seoFaq,
  }),
  makeTool({
    slug: "word-counter",
    title: "Word Counter",
    shortDescription: "Count words, characters, sentences, and reading time for any text.",
    category: "productivity",
    icon: "Hash",
    gradient: "from-pink-500 to-rose-500",
    badge: "Text Analyzer",
    popular: true,
    keywords: ["word counter", "character count", "reading time calculator"],
    howToUse: ["Paste or type your text.", "View word, character, and sentence counts.", "Use reading time for blog planning."],
    formula: "words = split whitespace; reading time = words / 200 wpm",
    faq: seoFaq,
  }),
  makeTool({
    slug: "slug-generator",
    title: "Slug Generator",
    shortDescription: "Create SEO-friendly URL slugs from titles and headlines.",
    category: "productivity",
    icon: "Link2",
    gradient: "from-lime-500 to-green-500",
    badge: "SEO Utility",
    keywords: ["slug generator", "url slug", "seo friendly url"],
    howToUse: ["Enter a title or phrase.", "Preview the generated slug.", "Copy for CMS or blog URLs."],
    formula: "lowercase → remove special chars → spaces to hyphens",
    faq: seoFaq,
  }),
];
