import { makeTool } from "./makeTool";
import type { ToolConfig } from "../toolsConfig";

const socialFaq = [
  { question: "Is this tool free?", answer: "Yes. All Ranburg social media tools are free." },
  { question: "Is my data stored?", answer: "No. Inputs are processed in your browser only." },
  { question: "Can I use generated content commercially?", answer: "Yes. Tags, descriptions, and hashtags are yours to use." },
];

export const SOCIAL_TOOLS: ToolConfig[] = [
  makeTool({
    slug: "youtube-tags-generator",
    title: "YouTube Tags Generator",
    shortDescription: "Generate SEO-friendly YouTube video tags from your topic and keywords.",
    category: "productivity",
    icon: "Youtube",
    gradient: "from-red-600 to-red-500",
    badge: "YouTube SEO",
    popular: true,
    keywords: ["youtube tags generator", "youtube video tags", "youtube seo tags"],
    howToUse: ["Enter video topic and main keyword.", "Add niche and competitor terms.", "Copy comma-separated tags."],
    formula: "Topic + keyword + long-tail variations → tag list",
    faq: socialFaq,
  }),
  makeTool({
    slug: "youtube-description-generator",
    title: "YouTube Description Generator",
    shortDescription: "Create optimized YouTube video descriptions with timestamps and CTAs.",
    category: "productivity",
    icon: "FileText",
    gradient: "from-red-500 to-orange-500",
    badge: "YouTube SEO",
    popular: true,
    keywords: ["youtube description generator", "video description template", "youtube seo description"],
    howToUse: ["Enter video title and summary.", "Add links and timestamps.", "Copy formatted description."],
    formula: "Hook + summary + chapters + links + hashtags",
    faq: socialFaq,
  }),
  makeTool({
    slug: "youtube-hashtag-generator",
    title: "YouTube Hashtag Generator",
    shortDescription: "Generate relevant hashtags for YouTube Shorts and long-form videos.",
    category: "productivity",
    icon: "Hash",
    gradient: "from-rose-500 to-pink-500",
    badge: "YouTube SEO",
    keywords: ["youtube hashtag generator", "youtube hashtags", "shorts hashtags"],
    howToUse: ["Enter video topic.", "Select niche.", "Copy hashtag list (max 15 for YouTube)."],
    formula: "#topic + #niche + trending variants",
    faq: socialFaq,
  }),
  makeTool({
    slug: "instagram-hashtag-generator",
    title: "Instagram Hashtag Generator",
    shortDescription: "Generate Instagram hashtag sets for posts, reels, and stories.",
    category: "productivity",
    icon: "Instagram",
    gradient: "from-purple-500 via-pink-500 to-orange-400",
    badge: "Instagram SEO",
    popular: true,
    keywords: ["instagram hashtag generator", "instagram hashtags", "reels hashtags"],
    howToUse: ["Enter post topic and niche.", "Choose broad, niche, and branded tags.", "Copy up to 30 hashtags."],
    formula: "Broad + niche + branded hashtag mix",
    faq: socialFaq,
  }),
  makeTool({
    slug: "instagram-engagement-calculator",
    title: "Instagram Engagement Calculator",
    shortDescription: "Calculate Instagram engagement rate from likes, comments, and followers.",
    category: "financial",
    icon: "Heart",
    gradient: "from-pink-500 to-rose-500",
    badge: "Social Analytics",
    keywords: ["instagram engagement calculator", "engagement rate instagram", "ig engagement"],
    howToUse: ["Enter followers, likes, and comments.", "View engagement rate percentage.", "Benchmark against industry averages."],
    formula: "((likes + comments) / followers) × 100",
    faq: socialFaq,
  }),
  makeTool({
    slug: "tiktok-engagement-calculator",
    title: "TikTok Engagement Calculator",
    shortDescription: "Calculate TikTok engagement rate from views, likes, comments, and shares.",
    category: "financial",
    icon: "TrendingUp",
    gradient: "from-slate-800 to-slate-900",
    badge: "Social Analytics",
    keywords: ["tiktok engagement calculator", "tiktok engagement rate"],
    howToUse: ["Enter views, likes, comments, shares.", "View engagement rate.", "Compare video performance."],
    formula: "((likes + comments + shares) / views) × 100",
    faq: socialFaq,
  }),
  makeTool({
    slug: "tiktok-earnings-calculator",
    title: "TikTok Earnings Calculator",
    shortDescription: "Estimate TikTok creator fund and brand deal earnings from views and RPM.",
    category: "financial",
    icon: "DollarSign",
    gradient: "from-teal-500 to-cyan-500",
    badge: "Creator Revenue",
    keywords: ["tiktok earnings calculator", "tiktok money calculator", "creator fund estimate"],
    howToUse: ["Enter monthly views or per-video views.", "Set RPM or CPM estimate.", "View projected earnings."],
    formula: "earnings = (views / 1000) × RPM",
    faq: [
      ...socialFaq,
      { question: "Are earnings guaranteed?", answer: "No. This is an estimate based on your inputs. Actual TikTok payouts vary by region and program." },
    ],
  }),
  makeTool({
    slug: "social-media-character-counter",
    title: "Social Media Character Counter",
    shortDescription: "Count characters for Twitter/X, Instagram, LinkedIn, YouTube, and TikTok limits.",
    category: "productivity",
    icon: "Type",
    gradient: "from-blue-500 to-violet-500",
    badge: "Social Utility",
    popular: true,
    keywords: ["social media character counter", "twitter character count", "caption length"],
    howToUse: ["Paste your caption or post.", "View counts per platform limit.", "Trim to fit each network."],
    formula: "Unicode-aware character count vs platform limits",
    faq: socialFaq,
  }),
];
